- Tiltfile
We added support to use CAAPH to install cilium via helm controller in PR https://github.com/linode/cluster-api-provider-linode/pull/96. By default, the addon is not installed when the management cluster is created from scratch. This PR installs the required addon when the management cluster is provisioned using tilt.
> install cilium-helm addon using tilt

- .github/workflows/gh-pages.yml
Based on https://github.com/actions/starter-workflows/blob/main/pages/mdbook.yml
> [gha] use upload pages artifact instead of writing to gh-pages branch

- README.md
> Update README.md with alpha warning

- .chainsaw.yaml
- .github/workflows/build_test_ci.yml
- Makefile
- e2e/kuttl-config.yaml
- e2e/linodecluster-controller/minimal-linodecluster/03-verify-nodebalancer.yaml
- e2e/linodecluster-controller/minimal-linodecluster/04-delete-linodecluster.yaml
- e2e/linodecluster-controller/minimal-linodecluster/05-verify-nodebalancer-destroyed.yaml
- e2e/linodecluster-controller/minimal-linodecluster/Makefile
- e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
Migrate from kuttl to chainsaw.
> chore: migrate from kuttl to chainsaw (linodecluster-controller)

- templates/flavors/base/kustomization.yaml
/kind bug
Fixes up #142: This adds the cluster credentials secret to the base `kustomization.yaml`.
Fixes #
Thanks @AshleyDumaine 😂  
**TODOs**:
> fixup: feat: multi-tenancy (#142)

- .github/workflows/build_test_ci.yml
> [GHA] - force log upload to overwrite existing logs

- controller/linodemachine_controller.go
/kind bug
adds back the empty LinodeCluster.
Fixes #
**TODOs**:
> [fix] - fix the machine scope

- cloud/scope/cluster.go
- cloud/scope/common.go
- cloud/scope/common_test.go
- cloud/scope/machine.go
- cloud/scope/object_storage_bucket.go
- cloud/scope/vpc.go
Minor refactor to createLinodeClient() to add some error handling if empty api key is passed in
Fixes #
**TODOs**:
> Small change to common_test.go

- .github/workflows/build_test_ci.yml
- README.md
/kind feature
This PR adds codecov reporting for all unit tests
Fixes #
**TODOs**:
> add codecov reporting

- .github/workflows/build_test_ci.yml
- Makefile
> [GHA] - add new target to catch uncommitted generated files in GHA, make sure to generate-mock target before testing

- Makefile
- e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
- e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
- e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
- e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/chainsaw-test.yaml
- e2e/linodevpc-controller/minimal-linodevpc/chainsaw-test.yaml
/kind cleanup
fixup! https://github.com/linode/cluster-api-provider-linode/pull/190: This passes the Git hash as an environment variable to Chainsaw rather than as a value. 
Fixes #190 
**TODOs**:
> fixup! e2e: template resources (#190)

- cloud/scope/client.go
- controller/linodemachine_controller.go
- mock/client.go
/kind bug 
Fixes #198 
**TODOs**:
> [fix] - wait up to 30 seconds for root disk to resize

- docs/src/topics/backups.md
- docs/src/topics/etcd.md
- docs/src/topics/flavors/etcd-backup-restore.md
- templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
> Add docs for etcd backups and set default for etcd backup restore image

- docs/src/developers/development.md
- docs/src/topics/flavors/default.md
- docs/src/topics/flavors/flavors.md
/kind documentation
Fixes #
**TODOs**:
> [docs] - update docs

- .tilt/ctlptl-config.yaml
- Tiltfile
- config/crd/kustomization.yaml
- templates/common-init-files/secret.yaml
- templates/flavors/base/secret.yaml
`clusterctl move` required we add a label which helps it discover the resource defined by CAPL CRDs and move it
Fixes #
**TODOs**:
> add clusterctl labels to allow clusterctl move command

- docs/src/topics/flavors/clusterclass-kubeadm.md
- docs/src/topics/flavors/default.md
- docs/src/topics/flavors/k3s.md
- docs/src/topics/flavors/rke2.md
> Fix quickstart links at flavors pages

- docs/src/topics/getting-started.md
> Fix flavors link at getting-started.md

- .github/workflows/build-push.yml
- .github/workflows/release.yml
- config/default/manager_image_patch.yaml
**What this PR does / why we need it**: Makes it so images are built and pushed for pushes to main, uses this image for the default image tag
Fixes #
**TODOs**:
> [GHA] - build and push images on main

- .github/workflows/build-push.yml
- .github/workflows/build_test_ci.yml
- .github/workflows/release.yml
> update release scripts to run tests before publishing an image

- .github/workflows/build-push.yml
- .github/workflows/build_test_ci.yml
> update workflow name in build-push job

- CONTRIBUTING.md
- docs/src/developers/development.md
> [doc] Basic code guidelines

- .github/ISSUE_TEMPLATE.md
- .github/workflows/gh-pages.yml
- .github/workflows/link-checker.yml
- .markdownlinkcheck.json
- CONTRIBUTING.md
- docs/src/reference/reference.md
- docs/src/topics/etcd.md
- docs/src/topics/flavors/dual-stack.md
- docs/src/topics/flavors/etcd-backup-restore.md
- templates/flavors/README.md
/kind documentation
**What this PR does / why we need it**: Fixes several dead links and splits out the link checking from the page deployment
Fixes #
**TODOs**:
> [GHA, docs] - Fix broken links

- .github/workflows/release.yml
> add go to release workflow

- Makefile
> fix release makefile target

- .github/workflows/release.yml
> Update release.yml to correctly upload release artifacts

- docs/src/topics/getting-started.md
> specify helm addon install in getting started

- .github/dependabot.yml
/kind cleanup
Fixes #
**TODOs**:
> update dependabot grouping for k8s deps

- .github/workflows/build-push.yml
/kind cleanup
Fixes #
**TODOs**:
> add git ref to CAPL image through build args

- metadata.yaml
> update releaseSeries metadata

- templates/flavors/k3s/k3sControlPlane.yaml
- templates/flavors/k3s/secret.yaml
- templates/flavors/rke2/rke2ConfigTemplate.yaml
- templates/flavors/rke2/rke2ControlPlane.yaml
- templates/flavors/rke2/secret.yaml
> move helmchart resources inline with k3s/rke2 resources

- controller/linodemachine_controller.go
> filter out linode already booted error messages when trying to create a machine

- .github/PULL_REQUEST_TEMPLATE.md
- .github/labels.yml
- .github/release-drafter.yml
- .github/workflows/build_test_ci.yml
- .github/workflows/release-drafter.yml
- CONTRIBUTING.md
add release drafter action
Fixes #
**TODOs**:
> [CI] add action to label PRs based on title and draft releases

- metadata.yaml
> add metadata support for capl version 0.3

- .github/workflows/release-drafter.yml
> [ci] fix drafter branch

- Makefile
- Tiltfile
- config/default/.gitignore
- config/default/kustomization.yaml
- config/default/manager-configmap.yaml
- config/default/manager_webhook_patch.yaml
This reverts commit 4ab0d88f2478313438adf1f732d0eaa8abdb7d9c in #291.
Fixes #291 
**TODOs**:
> [fix] revert "chore: add webhook toggle"

- .github/workflows/build_test_ci.yml
- .github/workflows/e2e-test.yaml
> Fix to allow e2e test child cluster egress

- .dockerignore
- Tiltfile
- config/manager/manager.yaml
- docs/src/developers/development.md
/kind testing
This PR adds support for debugging a cluster using [delve](https://github.com/go-delve/delve/blob/master/Documentation/cli/getting_started.md)
Fixes #
**TODOs**:
> [feat]: add support for a debug deploy option using delve

- docs/src/topics/flavors/cluster-autoscaler.md
- docs/src/topics/flavors/dual-stack.md
- docs/src/topics/flavors/etcd-backup-restore.md
- docs/src/topics/flavors/etcd-disk.md
- docs/src/topics/flavors/flavors.md
- docs/src/topics/flavors/vpcless.md
Add documentation for the new flavor combos
> [docs] Add docs for new flavors

- Makefile
- devbox.json
- devbox.lock
> [deps] upgrade devbox/Makefile tools versions to the latest versions

- templates/flavors/k3s/dual-stack/kustomization.yaml
- templates/flavors/k3s/full-vpcless/kustomization.yaml
- templates/flavors/k3s/vpcless/kustomization.yaml
> Fix k3s helmchart values for vpcless

- templates/flavors/k3s/dual-stack/kustomization.yaml
- templates/flavors/k3s/full-vpcless/kustomization.yaml
> [fix] Add patch for configtemplate for k3s for node-ip

- api/v1alpha1/linodecluster_types.go
- api/v1alpha1/linodemachine_types.go
- api/v1alpha1/linodeobjectstoragebucket_types.go
- api/v1alpha1/linodevpc_types.go
- api/v1alpha2/linodecluster_types.go
- cloud/scope/cluster.go
- cloud/scope/cluster_test.go
- cloud/scope/machine.go
- cloud/scope/machine_test.go
- cloud/scope/object_storage_bucket.go
- cloud/scope/object_storage_bucket_test.go
- cloud/scope/vpc.go
- cloud/scope/vpc_test.go
- controller/linodecluster_controller.go
- controller/linodemachine_controller.go
- controller/linodeobjectstoragebucket_controller.go
- controller/linodevpc_controller.go
- e2e/linodecluster-controller/minimal-linodecluster/assert-linodecluster.yaml
**What this PR does / why we need it**: This changes the finalizers to not have the api version in the finalizer string in line with other CAPI providers.
Fixes #
**TODOs**:
> [fix] finalizers to not contain the apiVersion

- templates/addons/cluster-autoscaler/cluster-autoscaler.yaml
- templates/addons/etcd-backup-restore/linode-obj.yaml
> [fix] update linodeobj and autoscaler template defaults

- cmd/main.go
- config/manager/manager.yaml
Bumped up the OTEL Semconv version, added downstream API for pod Name/Namespace, so they can be properly referenced in the manager.
N/A
**TODOs**:
> [improvement] OTEL semconv update

- docs/src/topics/getting-started.md
Fixes documentation gap in #380 
**TODOs**:
> fix formatting of clusterctl init command in docs

- .github/dependabot.yml
> [CI] group otel deps together in dependabot

- hack/observability/prometheus/values.yaml
This PR enables prometheus to keep metrics for 15 days (its default of prometheus as well)
Fixes #
**TODOs**:
> store data in prometheus for 15 days by default

- metadata.yaml
> [CI] Update metadata.yaml with 0.5 minor version

- templates/addons/ccm-linode/ccm-linode.yaml
When running at scale within VPC, older versions of ccm-linode were having data corruption issues. This is now fixed in linodego:v1.36.2 and ccm-linode:v0.4.10 is built with that version. Hence, updating the default version of ccm-linode in CAPL.
Fixes #
**TODOs**:
> [improvement] : update ccm-linode to v0.4.10

- controller/linodemachine_controller.go
- util/helpers.go
- util/helpers_test.go
**What this PR does / why we need it**: This introduces a new utility function that reconcilers can use to determine if they should requeue reconciliation to try again later
Fixes #
**TODOs**:
> [fix] account for retryable errors

- api/v1alpha1/linodecluster_conversion.go
- api/v1alpha1/linodecluster_conversion_test.go
- api/v1alpha1/linodeclustertemplate_conversion_test.go
- api/v1alpha1/linodemachine_conversion.go
- api/v1alpha1/linodemachine_conversion_test.go
- api/v1alpha1/linodemachinetemplate_conversion_test.go
- api/v1alpha1/linodevpc_conversion.go
- api/v1alpha1/linodevpc_conversion_test.go
- api/v1alpha2/linodecluster_conversion.go
- api/v1alpha2/linodemachine_conversion.go
- api/v1alpha2/linodevpc_conversion.go
this PR migrates remaining resources to conversion-gen functions and adds `*List` conversion test coverage
Fixes #
**TODOs**:
> [feat] migrate manual conversions to conversion-gen

- metadata.yaml
> [CI] Update metadata.yaml with 0.6 information

- config/rbac/role.yaml
- controller/linodeobjectstoragebucket_controller.go
- controller/linodeobjectstoragebucket_controller_test.go
- controller/linodeobjectstoragekey_controller.go
- controller/linodeobjectstoragekey_controller_test.go
- docs/src/topics/etcd.md
- envrc.example
- templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
- templates/addons/etcd-backup-restore/linode-obj.yaml
> [feat] Update etcd-backup flavor to use LinodeObjectStorageKey

- scripts/pre-kubeadminit.sh
This PR moves the apt install of containerd to a `curl` based install that allows us to control the containerd version better. This is needed for ubuntu 24.04 support which requires a newer containerd version to support new AppArmor defaults
Fixes #
**TODOs**:
> [improvement] update install script to support newer containerd versions

- templates/flavors/kubeadm/default/kubeadmConfigTemplate.yaml
- templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
> [fix] update kubeadm install script ref

- e2e/capl-cluster-flavors/k3s-capl-cluster/assert-child-cluster-resources.yaml
- e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
- templates/flavors/k3s/default/k3sConfigTemplate.yaml
- templates/flavors/k3s/default/k3sControlPlane.yaml
- templates/flavors/k3s/dual-stack/kustomization.yaml
- templates/flavors/k3s/full-vpcless/kustomization.yaml
- templates/flavors/k3s/vpcless/kustomization.yaml
> [deps] update k3s provider related templates to use version v1beta2

- api/v1alpha1/linodemachine_conversion_test.go
- api/v1alpha1/linodemachinetemplate_conversion_test.go
- api/v1alpha2/linodemachine_types.go
- cloud/services/domains_test.go
- cloud/services/loadbalancers.go
- cloud/services/loadbalancers_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
- controller/linodemachine_controller.go
- controller/linodemachine_controller_test.go
- util/helpers.go
- util/helpers_test.go
**What this PR does / why we need it**: InstanceID duplicates data while ProviderID is the standard way to set this information on machine resources.
Fixes #
**TODOs**:
> [deprecation] deprecate InstanceID

- cloud/services/domains.go
- cloud/services/domains_test.go
- controller/linodecluster_controller_test.go
linode dns entries fail to get deleted based on ownership. this pr fixes that. we now check for ownership on akamai entries too which we previously didnt
Fixes #
**TODOs**:
> [fix] fix dns record ownership

- api/v1alpha2/linodefirewall_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
- controller/linodefirewall_controller_helpers.go
**What this PR does / why we need it**: This makes it so the inbound/outbound default drop vs accept is determined directly by the FirewallSpec instead of trying to determine it by the rules present.
Fixes #
**TODOs**:
> [fix] set the inbound/outbound policy to whatever was specified instead of trying to determine by policy rules

- controller/linodecluster_controller.go
- controller/linodecluster_controller_helpers.go
- controller/linodecluster_controller_test.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
- controller/linodevpc_controller.go
- controller/linodevpc_controller_helpers.go
**What this PR does / why we need it**: General cleanup for controllers controller which should have helper functions in the appropriate helpers file for consistency
Fixes #
**TODOs**:
> [cleanup] move non-reconcile functions into controller helpers

- controller/linodecluster_controller.go
- controller/linodecluster_controller_test.go
- controller/linodemachine_controller.go
- e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
- e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
- e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
> [fix] remove ConditionLoadBalancing condition

- templates/addons/ccm-linode/ccm-linode.yaml
> [improvement] Bump CCM version

- templates/addons/ccm-linode/ccm-linode.yaml
> [improvement] Bump CCM to latest version

- templates/infra/linodeFirewall.yaml
- templates/infra/linodeVPC.yaml
We would like linodeVPC and linodeFirewall resources to use the same credentials which other resources are using and not use the default credentials of controller.
Fixes #
**TODOs**:
> [fix] : add credentials ref to linodeVPC and linodeFirewall templates

- templates/addons/etcd-backup-restore/linode-obj.yaml
**What this PR does / why we need it**: We add the `credentialsRef` to all other resources that support it in the spec by default.
Fixes #
**TODOs**:
> [fix] add default credentialsRef to bucket and key resources

- docs/src/SUMMARY.md
- docs/src/topics/firewalling.md
- docs/src/topics/placement-groups.md
This PR adds docs for the placement group feature and update firewall docs to include our current flavor integration
Fixes #
**TODOs**:
> [docs] add placement group docs and update firewall docs

- e2e/capl-cluster-flavors/rke2-capl-cluster/assert-child-cluster-resources.yaml
- e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
- templates/flavors/rke2/default/rke2ConfigTemplate.yaml
- templates/flavors/rke2/default/rke2ControlPlane.yaml
- templates/flavors/rke2/etcd-disk/kustomization.yaml
- templates/flavors/rke2/full-vpcless/kustomization.yaml
- templates/flavors/rke2/full/kustomization.yaml
- templates/flavors/rke2/vpcless/kustomization.yaml
This PR bumps the RKE resource versions to v1beta1 in our templates
Fixes #
**TODOs**:
> [deps] bump CAPRKE2 to use the v1beta1 spec

- templates/flavors/kubeadm/flatcar/patch-flatcar.yaml
> [fix] disable auto-update in the flatcar flavor

- .github/dependabot.yml
> [deps] group all otel dependencies together

- .golangci.yml
> disable golangci annotations on pull requests

- templates/flavors/k3s/dns-loadbalancing/kustomization.yaml
- templates/flavors/kubeadm/dns-loadbalancing/kustomization.yaml
- templates/flavors/rke2/dns-loadbalancing/kustomization.yaml
- templates/infra/linodeFirewall.yaml
> [fix] fix quoting of port in linodeFirewall

- controller/linodemachine_controller_helpers.go
**What this PR does / why we need it**: Follow-up from #537 since the linode API cares about the entire `StackScriptData` rather than just the `userdata` section of it.
Fixes #
**TODOs**:
> [fix] update stackscript size check for entire stackscript data instead of just userdata

- controller/linodecluster_controller.go
- controller/linodecluster_controller_test.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_test.go
This PR adds conditions for linodeVPC and linodeFirewall so that we can check if they are ready before continuing with provisioning of cluster/machines.
Fixes #
**TODOs**:
Add unittests
> [improvement] : add conditions to check if linodevpc and linodefirewall are ready

- .tilt/ctlptl-config.yaml
- Makefile
- Tiltfile
- devbox.json
- devbox.lock
- docs/src/developers/development.md
> [CI] add support for custom linode environments

- metadata.yaml
> [CI] Update metadata.yaml for 0.7.0 release

- .golangci.yml
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_helpers_test.go
- controller/linodemachine_controller_test.go
- controller/linodeplacementgroup_controller_helpers.go
- controller/linodevpc_controller_helpers.go
- controller/linodevpc_controller_helpers_test.go
**What this PR does / why we need it**: We're currently calling encode and decode for various objects which consumes a bit of CPU and memory. Instead, we explicitly convert the objects. This also bans the further use of gob going forward via depguard. 
Fixes #
**Special notes for your reviewer**: I also included the banning of reflect while enabling depguard. LMK if we for some reason don't want this.
**TODOs**:
> [improvement] remove gob to save memory

- .github/filters.yml
- e2e/capl-cluster-flavors/kubeadm-flatcar-vpcless-capl-cluster/chainsaw-test.yaml
- templates/flavors/kubeadm/flatcar/patch-flatcar.yaml
> [fix] disable LDE for flatcar

- controller/linodecluster_controller.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
**What this PR does / why we need it**: 400 errors shouldn't be immediately requeued since a configuration change is needed for the request to succeed. 
Fixes #
**TODOs**:
> [fix] don't immediately requeue if the error can't be fixed with a retry

- templates/addons/ccm-linode/ccm-linode.yaml
Since ccm versions 0.4.16 to 0.4.18 are marked as bad, we need to update to version 0.4.19 which has the fixes.
Fixes #
**TODOs**:
> [deps] : update ccm version for node internal ip fix

- metadata.yaml
> [CI] Update metadata.yaml for 0.8.0 release

- templates/addons/ccm-linode/ccm-linode.yaml
> [deps] : update ccm version

- README.md
> [docs] FIx README badge links

- internal/controller/linodemachine_controller_helpers.go
> [fix] Delete bootstrap data from object store only if provided

- api/v1alpha2/linodecluster_types.go
- api/v1alpha2/linodefirewall_types.go
- api/v1alpha2/linodemachine_types.go
- api/v1alpha2/linodeobjectstoragebucket_types.go
- api/v1alpha2/linodeobjectstoragekey_types.go
- api/v1alpha2/linodeplacementgroup_types.go
- api/v1alpha2/linodevpc_types.go
Currently, if we upgrade from v0.8.0 to later releases, reconcile fails for linodemachines provisioned using older code as their conditions don't have reason set. This causes capl reconcile to fail and it keeps on retrying infinitely with exponential backoff.
Fixes #
**TODOs**:
> [fix] : set reason to none if nothing specified

- docs/src/topics/getting-started.md
> [docs] update token permissions in getting started

- .github/workflows/e2e-upgrade-test.yaml
- Makefile
- e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
- e2e/kind-config.yaml
This PR allows us to provision mgmt cluster using previous release and then run latest main on it to make sure nothing breaks
Fixes #
**TODOs**:
> [CI] : add workflow to test upgrade

- .github/workflows/e2e-upgrade-test.yaml
I ended up merging https://github.com/linode/cluster-api-provider-linode/pull/636 when I intended to merge a different PR. As a result, ended up not updating the branch to main branch. This PR fixes it.
Fixes #
**TODOs**:
> [CI] : update GHA branch to correct branch

- Tiltfile
- config/default/manager_credentials_patch.yaml
- config/manager/manager.yaml
> simplify env-vars

- Tiltfile
- config/default/capl-ca.yaml
- config/default/kustomization.yaml
- config/manager/manager.yaml
This PR moves the logic for using custom CAs with CAPL from tilt into kustomize so future releases can use custom CAs with the capi-operator
Fixes #
**TODOs**:
> [improvement] add support for custom CAPL CAs in kustomize

- scripts/pre-kubeadminit.sh
Containerd doesn't merge plugin config options correctly https://github.com/containerd/containerd/issues/5837 
adding registry settings by default is safe - as the directories are ignored if they are empty. Users who want to use this will need to supply configuration in the `/etc/containerd/certs.d` directory, and containerd will automatically pick it up
Fixes #
**TODOs**:
> [feat] add registry settings to default containerd config

- templates/addons/ccm-linode/ccm-linode.yaml
Bumps CCM to most recent v0.4.23 release
Fixes #
**TODOs**:
> [deps] : update ccm to v0.4.23

- e2e/linodemachine-controller/cluster-object-store/assert-capi-resources.yaml
- e2e/linodemachine-controller/cluster-object-store/assert-key-and-secret.yaml
- e2e/linodemachine-controller/cluster-object-store/assert-linodemachine.yaml
- e2e/linodemachine-controller/cluster-object-store/chainsaw-test.yaml
- e2e/linodemachine-controller/cluster-object-store/check-linodemachine-deletion.yaml
- e2e/linodemachine-controller/cluster-object-store/create-cluster.yaml
- e2e/linodemachine-controller/cluster-object-store/create-linodemachine.yaml
- e2e/linodemachine-controller/cluster-object-store/create-linodeobjectstoragekey.yaml
Adds E2E tests for the [Cluster Object Store](https://linode.github.io/cluster-api-provider-linode/topics/cluster-object-store.html) feature.
Fixes #
This test runs on the following suites/selectors: `linodemachine`, `all`
**TODOs**:
> [test] e2e: linodemachine: cluster object store

- .github/workflows/go-analyze.yml
- .golangci.yml
- templates/addons/ccm-linode/ccm-linode.yaml
This PR bumps CCM version to v0.4.24 and also fixes the lint failures due to a URL getting blocked.
Fixes #
**TODOs**:
> [deps] [CI] : bump ccm version

- README.md
- docs/src/topics/getting-started.md
> [docs] : update readme, add info about management cluster

- templates/addons/ccm-linode/ccm-linode.yaml
> [deps] : bump ccm version to v0.4.25

- cmd/main.go
**What this PR does / why we need it**: It would be helpful to know what API URL is being used in the logs for debugging (though I set the level at info instead of debug, let me know if this should be different)
Fixes #
**TODOs**:
> [improvement] add info log for the api URL

- templates/addons/ccm-linode/ccm-linode.yaml
This PR bumps CCM to v0.5.2 which introduces k8s node cache and contains a fix for route_controller to not delete routes if node label is changed somehow.
Fixes #
**TODOs**:
> [deps] : update CCM to v0.5.2

- Makefile
> Update Makefile to bump CONVERSION_GEN_VERSION to v0.32.2

- .github/dependabot.yml
This update introduces a new pattern for AWS dependencies in the Dependabot configuration, allowing for automated updates of packages under the "github.com/aws/*". This enhancement improves dependency management for AWS-related libraries.
Fixes #
**TODOs**:
> [improvement] Add AWS dependency patterns to Dependabot configuration

- templates/addons/csi-driver-linode/linode-csi.yaml
> [deps] bump CSI driver to v1.0.6

- templates/addons/cilium/cilium.yaml
> [deps] bump cilium to 1.17.4

- .github/workflows/release.yml
See: https://github.com/softprops/action-gh-release/issues/628
**TODOs**:
> [deps] pin gh-release action version due to broken latest release

- internal/controller/linodemachine_controller_helpers.go
**What this PR does / why we need it**: Respects `.Spec.Tags` and consolidates it with the tag annotations so the tags for the instance are unique.
Fixes #
**TODOs**:
> [fix] continue to use .Spec.Tags until it is actually removed from the CRD

- metadata.yaml
> Update metadata.yaml to support v0.9.x

- .github/workflows/e2e-test.yaml
- .github/workflows/pr-labeler.yml
> [ci] set the ref for e2e-test and pr-labeler

- .github/workflows/build_test_ci.yml
- .github/workflows/e2e-test.yaml
- .github/workflows/e2e-upgrade-test.yaml
- .github/workflows/go-analyze.yml
- .github/workflows/pull_request_ci.yaml
> [CI] apparently we also need cdn.dl.k8s.io:443 too
