linode/cluster-api-provider-linode

- .gitignore
- Makefile
- README.md
- Tiltfile
- cmd/main.go
- ctlptl-config.yaml
This change introduces a basic Tilt setup for local development.
Fixes: https://github.com/linode/cluster-api-provider-linode/issues/30
> Introduce Tilt for local development

- Makefile
- Tiltfile
This PR is an initial change to deploy sigs.k8s.io/cluster-api to the target Tilt cluster.
> Install Cluster API on Tilt via clusterctl

- cmd/main.go
- go.mod
- go.sum
When the Go runtime starts it creates an OS thread for each CPU core. This means if you have a 16 core machine the Go runtime will create 16 OS threads - regardless of any CGroup CPU Limits. The Go runtime then uses these OS threads to schedule goroutines.
The problem is that the Go runtime is not aware of the CGroup CPU limits and will happily schedule goroutines on all 16 OS threads. This means that the Go runtime will expect to be able to use 16 seconds of CPU time every second.
Long stop the world durations arise from the Go runtime needing to stop Goroutine on threads that it’s waiting for the Linux Scheduler to schedule. These threads will not be scheduled once the container has used it’s CPU quota.
For more info please follow: https://www.riverphillips.dev/blog/go-cfs
> Set GOMAXPROCS automatically

- .husky/hooks/pre-commit
- .husky/hooks/pre-push
- Makefile
Git hooks are a great way to save time by running basic validations before git push and wait for CI result. It is an optional feature, devs has to opt in by executing `husky install`
> Introduce Husky git hook manager

- .github/workflows/build_test_ci.yml
- .github/workflows/codeql.yml
- .golangci.yml
- .husky/hooks/pre-push
- Makefile
- api/v1alpha1/linodemachine_types.go
- cloud/scope/cluster.go
- cloud/scope/machine.go
- cmd/main.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
- controller/suite_test.go
Golangci-lint, Gosec, Govulncheck and Nilaway has been introduced. CodeQL Github also has been added.
Fixes: https://github.com/linode/cluster-api-provider-linode/issues/44
> Introduce static code analysis

- Tiltfile
ensure all resources are categorized in the Tiltfile and limit docker build file watchers to go files
> clean up tiltfile

- Makefile
Originally `amd64` was hard coded to the download path of some dependencies, this fix make it architecture "independent".
> Fix dependency downloads by architecture in Makefile

- api/v1alpha1/linodecluster_types.go
- api/v1alpha1/linodemachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
- `lc` shortName for `LinodeClusters`
- `lm` shortName for `LinodeMachines`
- additional printer columns on `LinodeMachines` for State, Ready, InstanceID, and Machine
- adds the `cluster-api` category on `LinodeMachines` and `LinodeClusters` so they appear when running `kubectl get cluster-api`
- scopes `LinodeClusters` and `LinodeMachines` to be namespaced for consistency
> [tweak]: Add additional printer columns, shortnames, and cluster-api category

- controller/linodemachine_controller.go
I was hitting issues specifically for `LinodeMachines` that were part of a `KubeadmControlPlane`. They would be stuck in `Provisioning` (seems to be the initial status) on the associated `Machine` and hence they never properly reconciled to where they were actually created on the Linode side. 
e.g.:
```
k get cluster-api
NAME                                                                      CLUSTER      AGE
kubeadmconfig.bootstrap.cluster.x-k8s.io/adumaine-1-control-plane-hvb2q   adumaine-1   4m46s
kubeadmconfig.bootstrap.cluster.x-k8s.io/adumaine-1-md-0-ww2w2            adumaine-1   4m47s
NAME                                                               AGE
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/adumaine-1-md-0   4m47s
NAME                                  CLUSTERCLASS …
```
> [fix]: fix status check on created LinodeMachines

- cloud/scope/machine.go
- config/rbac/role.yaml
- controller/linodecluster_controller.go
- controller/linodemachine_controller.go
- util/reconciler/defaults.go
This modifies the `LinodeMachine` controller to wait for bootstrap data to be ready before creating Linode instances since the cloud-config needs to be stored in the metadata field to configure the Linode properly. Additionally sets swap to be disabled since kubeadm fails with swap enabled.
Related issues:
- https://github.com/linode/cluster-api-provider-linode/issues/1
- https://github.com/linode/cluster-api-provider-linode/issues/3
> [feat]: Set metadata for LinodeMachines, disable swap

- cloud/services/loadbalancers.go
- controller/linodemachine_controller.go
We need to enable private IPs on created Linodes in order to add control plane nodes to the NodeBalancer. 
This change will add any new control plane nodes to the NB backend automatically which does eventually go to "up" on the status check in Cloud Manager.
> [feat]: Add private IP on Linodes and add control plane nodes to NodeBalancer backend nodes

- cmd/main.go
Addresses: https://github.com/linode/cluster-api-provider-linode/issues/76#issue-2111484116
I'm not sure we should be using a global `LINODE_TOKEN` for the operator (and all it's managed workload clusters) here. We should allow workload clusters to specify the Linode account in which to provision its resources.
> fixup! Missing LINODE_TOKEN error message

- .github/workflows/build_test_ci.yml
- .github/workflows/codeql.yml
Go 1.22 is not compatible with controller-gen 0.13:
```
/home/runner/work/cluster-api-provider-linode/cluster-api-provider-linode/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0e55e]
goroutine 221 [running]:
go/types.(*Checker).handleBailout(0xc000cef200, 0xc00282bd40)
/opt/hostedtoolcache/go/1.22.0/x64/src/go/types/check.go:367 +0x88
panic({0xbc8860?, 0x12b9880?})
/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdc4c38, 0x12c2040}) …
```
> Use Go 1.21 in Github Actions

- .github/workflows/build_test_ci.yml
- Makefile
- cloud/scope/cluster.go
- config/manager/manager.yaml
- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_helpers_test.go
- e2e/Makefile
- e2e/README.MD
- e2e/kuttl-config.yaml
- e2e/linodecluster-controller/minimal/00-assert.yaml
- e2e/linodemachine-controller/minimal/00-assert.yaml
- e2e/linodemachine-controller/minimal/01-assert.yaml
- e2e/linodemachine-controller/minimal/01-create-cluster.yaml
- e2e/linodemachine-controller/minimal/02-assert.yaml
- e2e/linodemachine-controller/minimal/02-create-linodemachine.tpl.yml
- e2e/linodemachine-controller/minimal/02-create-linodemachine.yaml
- e2e/linodemachine-controller/minimal/03-delete-linodemachine.yaml
- e2e/linodemachine-controller/minimal/03-error.yaml
- e2e/linodemachine-controller/minimal/04-verify-linode-instance.yaml
- e2e/linodemachine-controller/minimal/Makefile
- e2e/linodevpc-controller/minimal/00-assert.yaml
- go.mod
- util/reconciler/defaults.go
At the time of this PR repo secrets are not available on forked repos, so this PR is a replication of https://github.com/linode/cluster-api-provider-linode/pull/71
> Some small bugfixes came around the test execution itself, so business logic didn't change compare to the original PR.
> Basic E2E test for machine controller

- cloud/scope/cluster.go
- cloud/scope/machine.go
- cloud/scope/vpc.go
fix: Stop controllers from constantly reconciling their objects due to overly-aggressive patching in `cloud/scope.AddFinalizer` methods
> fix: reconciliation spam for controllers 

- controller/linodemachine_controller_helpers.go
> [fix]: validate decoded bootstrap data does not exceed the user_data byte limit according to the Linode API

- controller/linodevpc_controller_helpers.go
- e2e/linodemachine-controller/byovpc/01-vpc-create-options.json
- e2e/linodemachine-controller/byovpc/Makefile
- e2e/linodevpc-controller/minimal/01-assert.yaml
- e2e/linodevpc-controller/minimal/01-create-vpc.yaml
- e2e/linodevpc-controller/minimal/02-delete-vpc.yaml
- e2e/linodevpc-controller/minimal/02-error.yaml
- e2e/linodevpc-controller/minimal/03-verify-vpc.yaml
- e2e/linodevpc-controller/minimal/Makefile
This test suit creates a a vpc via vpc controller, deletes the vpc and verifies deletion.
Related to: https://github.com/linode/cluster-api-provider-linode/issues/7 and https://github.com/linode/cluster-api-provider-linode/issues/4
> E2E test vpc controller

- cloud/services/loadbalancers.go
- controller/linodecluster_controller.go
- controller/linodemachine_controller.go
This PR fixes an issue where checking for a cluster existing happens while stuff is in the process of deleting and some resources don't get deleted. just move the check until after we validate if we are doing a delete operation. this also changes the tagging in cloud manager to be based on cluster `name` instead of `uuid` for easier readability.
> wait until after delete step to check that linodeCluster still exists

- Tiltfile
- controller/linodemachine_controller_helpers.go
- templates/addons/cilium-helm.yaml
- templates/cluster-template.yaml
This adds CAAPH (https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm) into the KIND management created by Tilt to install Cilium via the helm controller. We are doing this instead of using `postKubeadmCommands` because we need to be able to retry in the case of transient failures with reaching the control plane.
Using this template, it is possible to set env vars and use `envstubst` to create a cluster in a one-liner:
```
envsubst "`printf '${%s} ' $(sh -c "env|cut -d'=' -f1")`" < templates/cluster-template.yaml | kubectl apply -f -
```
Result:
```
(⎈|kind-tilt:N/A) ~  clusterctl describe cluster adumaine-1
NAME                                                           READY  SEVERITY  REASON  SINCE  MESSAGE
Cluster/adumaine-1 …
```
> [feat]: add cluster template, use CAAPH to install cilium for the CNI

- templates/cluster-template.yaml
In order for the [linode-ccm](https://github.com/linode/linode-cloud-controller-manager) to correctly set the external and internal IPs for nodes in a cluster, the provider ID needs to be `linode://$(instanceID}`. See:
- https://github.com/linode/linode-cloud-controller-manager/blob/main/cloud/linode/common.go#L9
- https://github.com/linode/linode-cloud-controller-manager/blob/main/cloud/linode/instances.go#L111
> [fix] providerID must conform to linode://{instanceID} for node external/internal IP setting

- templates/cluster-template.yaml
Slight tweaks to handle the k8s version being specified with or without a v prefix, set the init script to exit earlier on failures, and escape the `$` for setting the version which is needed if doing `clusterctl generate cluster` instead of `envsubst`
> [fix]: tweaks for pre-init script

- Makefile
- README.md
- devbox.json
- devbox.lock
- e2e/Makefile
This PR adds support for [devbox](https://github.com/jetpack-io/devbox), it does not force any tool to use devbox but just supports the devbox version of the tool if it is present. if the Make target is not run within a devbox shell it reverts to the existing Makefile tool caching logic. Additionally, this PR fixes the tool Make targets so they are only run if the tool doesn't exist locally already(fixing a bug where some targets ran every time)
closes #87
> add support for devbox

- e2e/linodemachine-controller/byovpc/01-create-cluster.tpl.yml
- e2e/linodemachine-controller/minimal/01-create-cluster.yaml
This specifies a full `infrastructureRef` for all test steps. It is technically a no-op since the CAPI controller won't process paused Cluster objects.
> e2e: Set full infrastructureRef everywhere

- .github/workflows/release.yml
- .gitignore
- Makefile
- Tiltfile
- config/crd/kustomization.yaml
- config/default/kustomization.yaml
- config/default/linode-token-secret.yaml
- config/default/manager_credentials_patch.yaml
- config/default/manager_image_patch.yaml
- docs/src/SUMMARY.md
- docs/src/developers/releasing.md
- docs/src/topics/troubleshooting.md
- e2e/README.MD
- e2e/linodecluster-controller/minimal/00-assert.yaml
- e2e/linodemachine-controller/byovpc/00-assert.yaml
- e2e/linodemachine-controller/minimal/00-assert.yaml
- e2e/linodevpc-controller/minimal/00-assert.yaml
- metadata.yaml
- This shortens "cluster-api-provider-linode" to "capl" on k8s resources to follow other provider naming conventions. 
- Organizes the Makefile and removes some unused targets
- Includes kustomize tweaks so that we can produce infrastructure-components.yaml without templating in values. 
- Adds a new release target and GHA workflow based off of https://github.com/linode/linode-cloud-controller-manager/blob/main/.github/workflows/release.yml to build and release the manager image to dockerhub on **tags** (needs extra secrets set in the repo settings to push)
> shorten cluster-api-provider-linode to capl, add release process

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/labels.yml
- .github/release-drafter.yml
- CONTRIBUTING.md
- CONTRIBUTING.md based on https://github.com/linode/linode-cloud-controller-manager/blob/main/.github/CONTRIBUTING.md
- PR and issue templates
- release drafter
- labels
- dependabot for docker
- makes dependabot apply a cleanup label on the commits
> add CONTRIBUTING.md and github templates and labels

- .github/dependabot.yml
- CONTRIBUTING.md
- code-of-conduct.md
Github includes the code of conduct in the project overview so I moved that out. (e.g. https://github.com/linode/cluster-api-provider-linode/tree/code-of-conduct?tab=coc-ov-file)
This also changes the label dependabot will use since we have an existing dependencies label.
> Code of conduct + use existing dependencies label for dependabot

- e2e/linodevpc-controller/minimal/03-verify-vpc.yaml
- util/helpers.go
/kind bug
Currently, we name nodes as CLi-*. However, k8s registers nodes in lowercase and if we check the output of `kubectl get nodes`, all nodes are in lowercase.
```
root@CLi-7162b7cb893a4441b7fb30dc68cb0698:~# k get nodes
NAME                                   STATUS   ROLES           AGE   VERSION
cli-7162b7cb893a4441b7fb30dc68cb0698   Ready    control-plane   30m   v1.29.1
cli-72d7c4d5eb794425a1fb71cc1d075e69   Ready    control-plane   26m   v1.29.1
```
Similarly, kubelet uses a certificate which also contains nodename in lowercase.
```
root@CLi-7162b7cb893a4441b7fb30dc68cb0698:~# openssl x509 -in temp.crt -noout -text | grep "Subject"
Subject: O = system:nodes, CN = …
```
> change nodenames to lowercase

- templates/addons/linode-blockstorage-csi-driver/linode-bs-csi.yaml
/kind bug
The linode-blockstorage-csi-driver expects for the secretRef that the token field is `token`, not `apiToken` like in the linode-ccm:
- https://github.com/linode/linode-blockstorage-csi-driver/blob/main/helm-chart/csi-driver/templates/csi-secrets.yaml#L8
- https://github.com/linode/linode-cloud-controller-manager/blob/main/deploy/chart/templates/ccm-linode.yaml#L8
Fixes #
**TODOs**:
> [fix] - add token field to CRS secret for csi-driver chart

- controller/linodemachine_controller_helpers.go
- controller/linodevpc_controller_helpers.go
- e2e/Makefile
- e2e/linodevpc-controller/minimal/03-verify-vpc.yaml
- util/helpers.go
/kind cleanup
This PR switched to using linode machine names instead of UID for less confusion
Fixes #
**TODOs**:
> [tweak] - Switch linode labels to LinodeMachine Name instead of UID

- docs/src/flavors/clusterclass-kubeadm.md
- templates/addons/cilium/cilium.yaml
- templates/flavors/base/cluster.yaml
- templates/flavors/clusterclass-kubeadm/cluster-template.yaml
/kind bug
Cilium when installed has ipam mode set to cluster-pool. We have kube-controller-manager configured to provide podCIDRs to nodes. Cilium ignores these settings and itself allocates podCIDRs to nodes. With this change, we tell cilium to use the podCIDRs allocated to nodes by kube-controller-manager and use them.
We are also changing the podCIDR to be 10.192.0.0/10 which allows us to have 16k /24 subnets. This also allows us to avoid conflicting with linode specific private subnet.
Sample output:
```
root@rs1-control-plane-z8qt2:~# k get pod/kube-controller-manager-rs1-control-plane-z8qt2 -n kube-system -o yaml | grep cidr
- --allocate-node-cidrs=true
- --cluster-cidr=10.192.0.0/10
root@rs1-control-plane-z8qt2:~# …
```
> set ipam mode to kubernetes

- docs/src/topics/flavors/k3s.md
- docs/src/topics/flavors/rke2.md
- templates/flavors/k3s/k3sControlPlane.yaml
- templates/flavors/k3s/kustomization.yaml
- templates/flavors/rke2/kustomization.yaml
- templates/flavors/rke2/rke2ConfigTemplate.yaml
- templates/flavors/rke2/rke2ControlPlane.yaml
/kind cleanup
It's easy to forget to set the correct k8s version for k3s vs rke2 vs kubeadm when swapping between flavors. This makes the variables distinct so `KUBERNETES_VERSION` doesn't need to be set every time a different flavor is used.
Fixes #
**TODOs**:
> 🔧  [tweak] - use different k8s version vars for different flavors

- .tilt/ctlptl-config.yaml
- Makefile
- devbox.json
- devbox.lock
- docs/src/topics/addons.md
- templates/addons/csi-driver-linode/kustomization.yaml
- templates/addons/csi-driver-linode/linode-csi.yaml
- templates/flavors/default/kustomization.yaml
> Rename csi-driver to better short-name.

- controller/linodemachine_controller.go
- templates/flavors/rke2/rke2ConfigTemplate.yaml
- templates/flavors/rke2/rke2ControlPlane.yaml
/kind bug
Adds the private IP to the `node-ip` and the public IP to the `tls-san` config for RKE2 like we had to do for K3s so the TLS certs are valid. Without `node-ip`, the container logs can't be retrieved and without the `tls-san` addition on top of that, server joining stops working. Ideally we need to have registration done via [controlPlaneEndpoint registration though that's still in progress](https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/266).
I'm aware `hostname -I` is brittle with the ordering per the manpage, but I don't have a much better solution at this time for this workaround.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
> [fix] [rke2] - set node-ip, use internal-only-ips for rke2 registration, set the ip type properly for the machine addresses

- api/v1alpha1/linodemachine_types.go
- cloud/scope/machine.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
- docs/src/topics/multi-tenancy.md
/kind feature
Updates LinodeMachines to be able to supply an (optional) CredentialsRef field to override the credentials of their owner LinodeCluster.
This allows for a (potentially future) enhancement where clusters can provision Linode resources cross-account.
Fixes #
This is being introduced now (rather than when the feature is determined to be absolutely needed) to provide a more stable API during development. However, we may wait to add this feature since:
1. The setting introduced is optional. Adding it later would have no …
> feat: extend multi-tenancy for LinodeMachines

- Tiltfile
- docs/src/developers/development.md
Installs the RKE2 and K3S providers into the KIND cluster created by Tilt if env vars are set.
Fixes #155
**TODOs**:
> [dev tweak] - install rke2 and k3s providers in tilt cluster if env vars are set, update dev docs

- .golangci.yml
- cloud/scope/object_storage_bucket.go
- cloud/services/loadbalancers.go
- cloud/services/object_storage_buckets.go
- cmd/main.go
- controller/linodecluster_controller.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- controller/linodeobjectstoragebucket_controller.go
- controller/linodevpc_controller.go
- controller/linodevpc_controller_helpers.go
- controller/suite_test.go
/kind cleanup
- Turns on the `gci` linter for checking import ordering on lint. Interesting caveat with `gci`: https://github.com/daixiang0/gci/issues/135. For this reason, we exclude `gci` linter on `cmd/main.go` and `controller/suite_test.go`
- Turns off nlreturn
- Turns off gocyclo since it's abandoned
- Bumps cyclop to 17
Fixes #
**TODOs**:
> 🧹 [cleanup] golangci-lint updates

- .gitignore
- Makefile
- cloud/services/loadbalancers.go
- controller/linodemachine_controller.go
- controller/linodevpc_controller_helpers.go
- util/filter.go
- util/filter_test.go
- util/helpers_test.go
- version/version_test.go
/kind testing
Fixes #
**TODOs**:
> [testing] - add more coverage

- devbox.json
Currently the `GOROOT` path that devbox is causing `make generate-mock` to fail. This PR add the config to set up the correct `GOROOT` path to `/usr/local/go`
Fixes #
**TODOs**:
> [FIX]: Setting correct GOROOT on startup for devbox

- .github/workflows/build_test_ci.yml
- Tiltfile
- hack/manifests/core.yaml
- hack/manifests/helm.yaml
- hack/manifests/k3s.yaml
- hack/manifests/kubeadm.yaml
- hack/manifests/rke2.yaml
/kind feature
This PR replaces `clusterctl init ...` local_commands in tilt with usage of the cluster-api operator and installs of the resources directly. The main benefit of doing it this way is we can easily stream container logs and see the health of the various parts of the CAPL installation. this otherwise should be a no-op for other workflows
Fixes #
**TODOs**:
> use the cluster-api operator for tilt installs instead of clusterctl

- e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/chainsaw-test.yaml
We are adding an API call to delete the obj bucket that is created during obj e2e test
Fixes #
**TODOs**:
> Add deletion step to delete the empty bucket during obj e2e test

- cloud/services/loadbalancers.go
- config/crd/kustomization.yaml
- config/crd/patches/validation_in_linodeclusters.yaml
- config/crd/patches/validation_in_linodeclustertemplates.yaml
- config/crd/patches/validation_in_linodemachines.yaml
- config/crd/patches/validation_in_linodemachinetemplates.yaml
- config/crd/patches/validation_in_linodevpcs.yaml
- e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
- e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
- e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
/kind bug
This propagates the label constraints of Linode resources to their associated CAPL CustomResourceDefinitions via the Kubernetes Validation Rules feature. When a custom resource is created, the Kubernetes object name is validated against the label constraints of its backing Linode resources. This allows CAPL-managed resources to maintain a human-readable naming scheme between its Kubernetes representation and the backing Linode resource implementations.
See:
- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules
- https://github.com/kubernetes/kubernetes/issues/74620
**Testing**
1. Create `Linode*` resources with invalid names:
```sh
$ export …
```
> fix: add additional name validation for custom resources

- Makefile
**What this PR does / why we need it**: The 2 minute timeout sometimes isn't enough time for tilt-ci to finish, it can sometimes take up to 7 minutes. This instead falls back to the default tilt timeout of 30 minutes.
Fixes #
**TODOs**:
> remove tilt ci timeout

- docs/src/topics/getting-started.md
Fixing: `Error: failed to get repository client for the InfrastructureProvider with name linode: error creating the local filesystem repository client: invalid path: path "infrastructure-linode/0.0.0/infrastructure-components.yaml" must be an absolute path`
> Fix provider url at getting-started.md

- Makefile
- api/v1alpha1/linodemachine_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- cloud/scope/client.go
- cloud/services/stackscript.sh
- cloud/services/stackscripts.go
- cloud/services/stackscripts_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_helpers_test.go
- devbox.lock
- docs/src/topics/getting-started.md
- mock/client.go
- templates/flavors/base/linodeMachineTemplate.yaml
- util/filter.go
- util/filter_test.go
/kind feature
This PR introduced the option to use a stackscript instead of cloud-init to bootstrap a cluster. cloud-init support is currently only rolled out to a few datacenters and the Akamai datasource has only been added/backported to a few official Linode OSes. Datacenter capabilities are fairly static so from a deployed DC we can infer whether or not you need stackscript based bootstrapping. For OSes, it is harder to confidently infer this information so a flag `useStackScriptBootstrap` is introduced with the corresponding template variable `USE_STACKSCRIPT_BOOTSTRAP` to enable this functionality if your OS/DC needs it and it is not enabled automatically. Stackscript …
> add support for stackscript based bootstrapping

- .github/workflows/gh-pages.yml
**What this PR does / why we need it**: This will try to catch broken links in our docs (via https://github.com/ruzickap/action-my-broken-link-checker) before we publish them so we can address any issues if they arise.
Fixes #
**TODOs**:
> [GHA] check for broken links

- .golangci.yml
- api/v1alpha1/linodemachine_types.go
- api/v1alpha1/linodeobjectstoragebucket_types.go
- api/v1alpha1/linodevpc_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- cloud/scope/machine.go
- cloud/scope/machine_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragebuckets.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_helpers_test.go
- devbox.json
- devbox.lock
/kind feature
/kind cleanup
This PR does the following:
- adds support for turning of private IP
- add `linodevpc` & `linodeobjectstorage` controllers to the `cluster-api` group
- add short name `lvpc` for linodeVPC object
- print ready status when getting a `linodevpc`
- fixes `ID` and `IP` capitalization in our CRDs
The diff unfortunately got very screwed up while moving the `bootstrap` logic into it's own `setupUserdata` function but the main change for private IP support is just
```
if machineScope.LinodeMachine.Spec.PrivateIP != nil {
createConfig.PrivateIP = *machineScope.LinodeMachine.Spec.PrivateIP
} else {
createConfig.PrivateIP = true
}
``` 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
> add ability to turn off private IPs and fix some misc api spec fields

- cloud/scope/common.go
- cloud/scope/machine.go
- cloud/scope/machine_test.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_test.go
- util/reconciler/conditions.go
- util/reconciler/defaults.go
> [fix] Requeue during machine preflight

- docs/src/SUMMARY.md
- docs/src/topics/flavors/clusterclass-kubeadm.md
- docs/src/topics/flavors/dual-stack.md
- docs/src/topics/flavors/etcd-backup-restore.md
- docs/src/topics/flavors/k3s.md
- docs/src/topics/flavors/rke2.md
- templates/addons/cilium/cilium-ipv6.yaml
- templates/addons/cilium/kustomization.yaml
- templates/common-init-files/secret.yaml
- templates/flavors/dual-stack/kustomization.yaml
/kind feature
**What this PR does / why we need it**: Adds a new dual-stack flavor to enable ipv6 in kubeadm clusters. Also creates a different ipv6 HelmChartProxy for cilium since enabling ipv6 on cilium without the correct kubeadm settings to support ipv6 will keep cilium from starting properly.
Fixes #
**TODOs**:
> [feat] Create new dual-stack flavor

- Tiltfile
- docs/src/developers/development.md
/kind feature
**What this PR does / why we need it**: Now that we have a container image in dockerhub for the main branch, this change allows for the setting of an env var to bypass the docker build in Tilt to use the latest off main in Dockerhub instead.
Fixes #
**TODOs**:
> [tweak] make it possible to skip docker build in Tilt

- docs/src/SUMMARY.md
- docs/src/topics/disks/data-disks.md
- docs/src/topics/etcd.md
- docs/src/topics/flavors/etcd-disk.md
- templates/flavors/default/kubeadmControlPlane.yaml
- templates/flavors/etcd-disk/kustomization.yaml
/kind feature
**What this PR does / why we need it**: This creates a new flavor to configure etcd to be on a separate disk
Fixes #
**TODOs**:
> [feat] - add new etcd-disk flavor

- docs/src/topics/flavors/k3s.md
- docs/src/topics/flavors/rke2.md
- templates/common-init-files/secret.yaml
- templates/flavors/clusterclass-kubeadm/kubeadmConfigTemplate.yaml
- templates/flavors/clusterclass-kubeadm/kubeadmControlPlaneTemplate.yaml
- templates/flavors/default/kubeadmConfigTemplate.yaml
- templates/flavors/default/kubeadmControlPlane.yaml
- templates/flavors/k3s/k3sConfigTemplate.yaml
- templates/flavors/k3s/k3sControlPlane.yaml
- templates/flavors/k3s/kustomization.yaml
- templates/flavors/rke2/kustomization.yaml
- templates/flavors/rke2/rke2ConfigTemplate.yaml
- templates/flavors/rke2/rke2ControlPlane.yaml
/kind cleanup
This PR does some cleanup of our templates in a few ways
* executes common steps such as turning swap off in a consistent way across flavors
* removes providerID specification since the CCM can handle setting this correctly when it is installed
* sets all flavors to use the KUBERNETES_VERSION env variable so the `clusterctl --kubernetes-version` flag will work as expected
Fixes #
**TODOs**:
> standardize k8s version and common setup steps in templates

- Makefile
- docs/src/developers/development.md
- docs/src/developers/releasing.md
- docs/src/topics/backups.md
- docs/src/topics/etcd.md
- docs/src/topics/flavors/cluster-autoscaler.md
- docs/src/topics/flavors/clusterclass-kubeadm.md
- docs/src/topics/flavors/default.md
- docs/src/topics/flavors/dual-stack.md
- docs/src/topics/flavors/etcd-backup-restore.md
- docs/src/topics/flavors/etcd-disk.md
- docs/src/topics/flavors/k3s.md
- docs/src/topics/flavors/rke2.md
- docs/src/topics/getting-started.md
- docs/src/topics/health-checking.md
/kind documentation
Update docs to use newly released CAPL artifacts
Fixes #
**TODOs**:
> update docs to reflect installing CAPL from release artifacts

- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
/kind cleanup
This PR addresses issues reported by `trivy k8s --report all -n capl-system all` for pod workloads. 
Fixes #
**TODOs**:
> address vulnerabilities reported by a trivy scan of the running CAPL pods

- docs/src/topics/addons.md
- templates/addons/cilium/cilium-ipv6.yaml
- templates/addons/cilium/cilium.yaml
/kind feature
**What this PR does / why we need it**: This makes it so workload clusters using Cilium as the CNI can by default start using `CiliumBGPPeeringPolicies` to allow for Cilium to advertise routes to BGP routers.
Fixes #
**TODOs**:
> [feat] - enable cilium BGP control plane

- cloud/scope/client.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_test.go
- mock/client.go
/kind cleanup
This PR removes the `WaitForInstanceDiskStatus` polling call and instead will re-queue any call and suppress any errors if the Linode API response is `Linode Busy`(400 response code).
Fixes #
**TODOs**:
> remove wait for disk call and add retry for busy error code

- docs/src/topics/flavors/rke2.md
- templates/flavors/rke2/rke2ConfigTemplate.yaml
- templates/flavors/rke2/rke2ControlPlane.yaml
/kind feature
**What this PR does / why we need it**: Enables the [CIS profile](https://docs.rke2.io/security/hardening_guide#rke2-configuration) for the RKE2 flavor and adds some extra configuration for [CIS hardening](https://docs.rke2.io/security/hardening_guide). Unfortunately we can't use "cis" for RKE2 1.29 due to a CRD validation issue where that is not present in the enum. I've opened a [PR](https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/301) upstream for that in the meantime.
With an RKE2 cluster provisioned by CAPL with these changes, I ran a scan on it after installing the [`rancher-cis-benchmark` helm chart](https://github.com/rancher/charts/tree/dev-v2.9/charts/rancher-cis-benchmark/5.1.0):
```
lastRunScanProfileName: …
```
> [rke2] - enable cis-profile, add configuration for CIS hardening

- .github/workflows/build_test_ci.yml
- .github/workflows/go-analyze.yml
/kind cleanup
This moves the code to do static code analysis into it's own workflow file. This also removes the security/vuln checks as the codeql settings on the repo should also cover that
Fixes #
**TODOs**:
> create a separate workflow for go analyze

- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
- docs/src/developers/development.md
- docs/src/topics/getting-started.md
- templates/addons/cilium/cilium.yaml
- templates/addons/provider-linode/linode-ccm.yaml
- templates/common-init-files/secret.yaml
- templates/flavors/base/kustomization.yaml
- templates/flavors/base/linodeCluster.yaml
- templates/flavors/base/linodeMachineTemplate.yaml
- templates/flavors/base/linodeVPC.yaml
- templates/flavors/default/kubeadmControlPlane.yaml
- templates/flavors/k3s/k3sConfigTemplate.yaml
- templates/flavors/k3s/k3sControlPlane.yaml
- templates/flavors/k3s/secret.yaml
- templates/flavors/rke2/kustomization.yaml
- templates/flavors/rke2/rke2ConfigTemplate.yaml
- templates/flavors/rke2/rke2ControlPlane.yaml
- templates/flavors/rke2/secret.yaml
/kind feature
With this change, k8s clusters are provisioned by default within a VPC.
1. Since nodebalancers don't yet work with VPC subnets, we attach two interfaces to a linode:
- eth0 for public and private nodebalancer traffic
- eth1 for VPC pod-to-pod traffic
We have to keep pub+priv on eth0 because we want cloud-init to work within VPC. If eth0 is on VPC, then cloud-init fails unless we explicitly add route to make it go over eth1. Once nodebalancer and cloud-init works natively with VPC, we'll use just one interface.
2. We have cilium installed and configured with native routing (no vxlan). All pod-to-pod traffic goes over eth1 within the VPC.
```
root@rah6-control-plane-g8zh6:~# ip a | grep vxlan …
```
> add vpc support for capl clusters

- Makefile
- docs/src/developers/development.md
- docs/src/topics/backups.md
- docs/src/topics/etcd.md
- docs/src/topics/flavors/cluster-autoscaler.md
- docs/src/topics/flavors/clusterclass-kubeadm.md
- docs/src/topics/flavors/default.md
- docs/src/topics/flavors/dual-stack.md
- docs/src/topics/flavors/etcd-backup-restore.md
- docs/src/topics/flavors/etcd-disk.md
- docs/src/topics/flavors/k3s.md
- docs/src/topics/flavors/rke2.md
- docs/src/topics/getting-started.md
- docs/src/topics/health-checking.md
/kind cleanup
Based on feedback on https://github.com/kubernetes-sigs/cluster-api/pull/10471 this changes our documentation to use `linode-linode` instead of `akamai-linode`. it also separates out the naming for locally built manifest files into `local-linode` though I would be open to keeping this the same as `linode-linode`
Fixes #
**TODOs**:
> update provider name in documentation to linode-linode

- devbox.json
- devbox.lock
- go.mod
/kind cleanup
add go toolchain and update devbox to 1.22.2
Fixes #
**TODOs**:
> set toolchain to go1.22.2 in go.mod and update devbox go version to match

- docs/src/topics/addons.md
- docs/src/topics/flavors/clusterclass-kubeadm.md
- docs/src/topics/troubleshooting.md
- templates/addons/cilium/cilium-ipv6.yaml
- templates/addons/cilium/cilium-vxlan.yaml
- templates/addons/cilium/cilium.yaml
- templates/addons/csi-driver-linode/linode-csi.yaml
- templates/addons/provider-linode/linode-ccm-vpcless.yaml
- templates/addons/provider-linode/linode-ccm.yaml
- templates/flavors/clusterclass-kubeadm/cluster-template.yaml
- templates/flavors/default/kustomization.yaml
- templates/flavors/rke2/kustomization.yaml
**What this PR does / why we need it**: helmchartproxy objects should be unique for each cluster so that we can have settings per cluster. This PR fixes it.
Fixes #
**TODOs**:
> generate unique helmchartproxy names

- cloud/scope/cluster.go
- cloud/scope/cluster_test.go
- cloud/scope/common.go
- cloud/scope/common_test.go
- cloud/scope/machine.go
- cloud/scope/machine_test.go
- cloud/scope/vpc.go
- cloud/scope/vpc_test.go
- controller/linodecluster_controller.go
- controller/linodemachine_controller.go
- controller/linodevpc_controller.go
/kind cleanup
Adds a unique finalizer to the credentials reference Secret (if `.spec.CredentialsRef` is set) when creating `Linode{Cluster,Machine,VPC}` resources and removes it upon deletion. The finalizer is unique in case you have a shared Secret (e.g. `KIND.GROUP/NAMESPACE.NAME`).
Fixes #
This allows users to use `kubectl delete` with the output of `clusterctl generate`, e.g.:
```sh
clusterctl generate cluster $CLUSTER_NAME \
--kubernetes-version v1.29.1 \
--infrastructure akamai-linode:v0.0.0 \
--flavor clusterclass-kubeadm \ …
```
> fix: add finalizer to credentials reference

- docs/src/SUMMARY.md
- docs/src/developers/development.md
- docs/src/developers/testing.md
> Add testing page to mdbook

- .github/workflows/build_test_ci.yml
- .github/workflows/e2e-test.yaml
- Makefile
- docs/src/developers/testing.md
- e2e/capl-cluster-flavors/default-CAPL-cluster/chainsaw-test.yaml
- e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
- e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
- e2e/linodecluster-controller/minimal-linodecluster/chainsaw-test.yaml
- e2e/linodemachine-controller/minimal-linodemachine/chainsaw-test.yaml
- e2e/linodemachine-controller/vpc-integration/chainsaw-test.yaml
- e2e/linodeobjectstoragebucket-controller/minimal-linodeobjectstoragebucket/chainsaw-test.yaml
- e2e/linodevpc-controller/minimal-linodevpc/chainsaw-test.yaml
> split out e2e tests into its own gha file

- api/v1alpha1/webhook_helpers.go
- cloud/scope/cluster.go
- cloud/scope/common.go
- cloud/scope/common_test.go
- cloud/scope/machine.go
- cloud/scope/object_storage_bucket.go
- cloud/scope/vpc.go
/kind cleanup
**What this PR does / why we need it**: [The default http client should not be used in production since there is no timeout configured](https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779). This instead configures the unauthenticated client to use a timeout and also adds that timeout setting to the linode client created for the other resources. This also changes the default webhook timeout from a minute to 30s. 10 seconds is the default: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts
Fixes #
**Special notes for your …
> [tweak] - set timeout for default http clients, reduce webhook timeout

- PROJECT
- api/v1alpha1/linodecluster_types.go
- api/v1alpha1/linodecluster_webhook.go
- api/v1alpha1/linodecluster_webhook_test.go
- api/v1alpha1/webhook_suite_test.go
- cmd/main.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
- config/crd/kustomization.yaml
- config/webhook/manifests.yaml
/kind feature
Adds a validating admission webhook for `infrastructure.cluster.x-k8s.io/v1alpha1/linodecluster` resources on creation.
This initial validation webhook validates the following LinodeCluster resource fields on object creation:
| **Field**      | **Validation(s)** |
| -------------- | ----------------- |
| `.spec.region` | Valid region      |
Fixes #
**TODOs**:
**Testing**:
1. Create an invalid `LinodeCluster` resource:
```sh
$ kubectl apply -f - <<EOF
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: …
```
> feat: linodecluster: add validating admission webhook on create

- PROJECT
- api/v1alpha1/linodeobjectstoragebucket_webhook.go
- api/v1alpha1/linodeobjectstoragebucket_webhook_test.go
- api/v1alpha1/webhook_helpers.go
- api/v1alpha1/webhook_suite_test.go
- cmd/main.go
- config/crd/kustomization.yaml
- config/crd/patches/cainjection_in_linodeobjectstoragebuckets.yaml
- config/crd/patches/webhook_in_linodeobjectstoragebuckets.yaml
- config/webhook/manifests.yaml
/kind feature
Adds a validating admission webhook for `infrastructure.cluster.x-k8s.io/v1alpha1/linodeobjectstoragebucket` resources on creation.
This initial validation webhook validates the following LinodeCluster resource fields on object creation:
| **Field**       | **Validation(s)**                                                                                                                                    |
| --------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- |
| `.spec.cluster` | - Format: REGION_ID-ORDINAL<br>- Region:  Valid, [Object Storage …
> [feat]: linodeobjectstoragebucket: add validating admission webhook on create

- e2e/admission-webhooks/validating/assert-capl-resources.yaml
- e2e/admission-webhooks/validating/chainsaw-test.yaml
- e2e/admission-webhooks/validating/invalid-linodecluster.yaml
- e2e/admission-webhooks/validating/invalid-linodemachine.yaml
- e2e/admission-webhooks/validating/invalid-linodeobjectstoragebucket.yaml
- e2e/admission-webhooks/validating/invalid-linodevpc.yaml
/testing
Adds an e2e test against the admission validation of the following resources:
- LinodeCluster
- LinodeMachine
- LinodeVPC
- LinodeObjectStorageBucket
Fixes #
**TODOs**:
> [CI] e2e: add validating admission webhooks test

- scripts/add-kubeadm-required-files.sh
cloud-init has a limit of 16k bytes. With current changes, our generated cloud-init user-data for kubeadm default flavor is close to 16k bytes. We need to reduce the usage of user-data and one option is to have the script downloaded in cloud-init to generate static files than uploading static files via cloud-init.
This PR adds script which can be used to generate the static files. We intentionally don't remove config from cloud-init in this PR as that will be removed in subsequent PRs which starts using the newly added script. This script is a temporary workaround until we have golden images where we can have containerd and other required settings configured by default.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
> [improvement]: add static files required by kubeadm using script than cloud-init

- templates/flavors/kubeadm/default/kubeadmConfigTemplate.yaml
- templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
We are hitting cloud-init limits of 16k for kubeadm flavor clusters and would like to reduce the size of cloud-init userdata. This PR enables us to use script instead of hardcoding data into cloud-init's userdata.
Fixes #
**TODOs**:
> [improvement]: reduce cloud-init size, use script for kubeadm

- templates/addons/cilium-network-policies/ciliumNetworkPolicies.yaml
- templates/flavors/kubeadm/default/allow-etcd-policy.yaml
- templates/flavors/kubeadm/default/kustomization.yaml
kustomize is currently not detecting the ccnp patch for kubeadm to add etcd ports. This is down to kustomize not using env vars and failing to find a matching resources. Se we are now adding a etcd specific policy for kubeadm
> [fix] Create new ccnp for etcd ports

- templates/addons/csi-driver-linode/linode-csi.yaml
This pull request bumps the version of `linode-blockstorage-csi-driver` to [v0.7.0](https://github.com/linode/linode-blockstorage-csi-driver/releases/tag/v0.7.0).
This version of the CSI driver allows for attaching >8 Linode Block Storage Volumes to Kubernetes nodes with >=16GB of RAM.
> [deps] addons/csi-driver-linode: Bump to v0.7.0

- templates/flavors/k3s/dual-stack/kustomization.yaml
- templates/flavors/k3s/full-vpcless/kustomization.yaml
- templates/flavors/k3s/vpcless/kustomization.yaml
- templates/flavors/kubeadm/dual-stack/kustomization.yaml
- templates/flavors/kubeadm/full-vpcless/kustomization.yaml
- templates/flavors/kubeadm/vpcless/kustomization.yaml
- templates/flavors/rke2/vpcless/kustomization.yaml
**What this PR does / why we need it**: I noticed of our current 28 generated flavors, 8 of them were missing the default cilium host FW. This adds that to 7 of them (not sure about the clusterclass patch needed at this time)
Fixes #
**TODOs**:
> [fix] flavors beside clusterclass that were missing cilium host FW

- templates/flavors/k3s/full-vpcless/kustomization.yaml
- templates/flavors/k3s/vpcless/kustomization.yaml
- templates/flavors/rke2/vpcless/kustomization.yaml
We updated the version for linodecluster to v1alpha2. We missed updating patches for vpcless installs for rke2 and k3s. This PR updates the version in patch to correct version.
Fixes #
**TODOs**:
> [fix]: fix version of linodecluster to correctly patch targets

- .github/workflows/release.yml
- scripts/add-kubeadm-required-files.sh
- scripts/pre-kubeadminit.sh
- templates/flavors/kubeadm/default/kubeadmConfigTemplate.yaml
- templates/flavors/kubeadm/default/kubeadmControlPlane.yaml
**What this PR does / why we need it**: This switches to installing the kubeadm packages with tar files intead of apt and moves kubeadm setup into a single script.
Fixes #
**TODOs**:
> [cleanup] switch to not using apt for kubeadm, kubelet, and kubectl, curl kubeadm pre-init script

- templates/flavors/k3s/dual-stack/kustomization.yaml
- templates/flavors/k3s/full-vpcless/kustomization.yaml
**What this PR does / why we need it**: In VPC-less environments we need to manually set the node-ip until the CCM can take over. This cannot be done with `kubelet-arg` since that prevents the nodes from getting the externalIP set from the CCM. Instead, this uses `node-ip` like before, but includes the ipv6 address needed for k3s not to complain about a dual-stack cluster-cidr but an ipv4-only `node-ip`.
With this change for k3s-dual-stack:
```
(⎈|test-cluster-admin@test-cluster:N/A) ~  k get no -o wide
NAME                               STATUS   ROLES                       AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
test-cluster-control-plane-pwwg8   Ready    control-plane,etcd,master   88s   v1.29.1+k3s2   <none> …
```
> [bugfix] cannot use kubelet-arg to set node-ip for k3s

- config/default/linode-token-secret.yaml
- templates/infra/secret.yaml
If LINODE_DNS_TOKEN is not set in the env, we see
```
clusterctl init --infrastructure linode-linode --addon helm  --bootstrap k3s --control-plane k3s 
Fetching providers
Error: failed to get provider components for the "linode-linode" provider: failed to perform variable substitution: value for variables [LINODE_DNS_TOKEN] is not set. Please set the value using os environment variables or the clusterctl config file
```
This fix defaults the LINODE_DNS_TOKEN in controller secret to LINODE_TOKEN if not set in the env
Fixes #
**TODOs**:
> [fix] set default value for dns token to be the linode api token

- templates/flavors/kubeadm/konnectivity/kustomization.yaml
We moved away from apt and started installing packages from tar files in PR https://github.com/linode/cluster-api-provider-linode/pull/366. We missed doing that change for konnectivity and its broken because of it. This PR fixes installs for kubeadm-konnectivity flavor.
Fixes #
**TODOs**:
> [fix] : fix konnectivity installs as we are now installing packages from tar files

- controller/linodemachine_controller.go
Our project bumped to v0.4.0 of the CAPL provider and are attempting to use only v1alpha2 LinodeClusters now. When setting the v1alpha1 CRD to not be served, it causes our controller to crash loop as [v1alpha1 LinodeMachines only watch v1alpha1 LinodeClusters](https://github.com/linode/cluster-api-provider-linode/blob/46a73028de6c14c0290a3a4423acb499aa9f3f93/controller/linodemachine_controller.go#L732-L735). 
Fixes #
**TODOs**:
> update v1alpha1 machines to watch v1alpha2 clusters

- api/v1alpha1/linodecluster_webhook.go
- api/v1alpha1/linodemachine_webhook.go
- api/v1alpha1/linodeobjectstoragebucket_webhook.go
- api/v1alpha1/linodevpc_webhook.go
- api/v1alpha2/linodecluster_webhook.go
- config/webhook/manifests.yaml
After bumping to use v1alpha2 `LinodeClusters` in a capi project, I cannot apply the `config/webhooks` directory via kustomize+tilt as both the v1alpha1 and v1alpha2 `LinodeCluster` webhooks are named `vlinodecluster.kb.io` (error below). This is due to a (potential) typo in the `//+kubebuilder:webhook:....` auto-generation comments for all custom resources: `vlinodemachine.kb.io`, `vlinodevpc.kb.io`, `vlinodecluster.kb.io`, and `vlinodeobjectstoragebucket.kb.io`. `LinodeClusters` are the first custom resource to introduce a new api version which is why the issue is only seen for those webhooks.
```log
Build Failed: ValidatingWebhookConfiguration.admissionregistration.k8s.io "capi-validating-webhook-configuration" is invalid: webhooks[1].name: …
```
> [fix] bug where v1alpha1/2 linodecluster webhooks have same auto-generated name 

- clients/clients.go
- cloud/services/loadbalancers.go
- cloud/services/loadbalancers_test.go
- controller/linodecluster_controller.go
- controller/linodecluster_controller_test.go
- mock/client.go
- observability/wrappers/linodeclient/linodeclient.gen.go
**What this PR does / why we need it**: Currently if a `LinodeCluster` resource is created and the nodebalancer ID/nodebalancer Config ID is specified but not the control-plane endpoint CAPL cannot handle this case, e.g.:
```
spec:
controlPlaneEndpoint:
host: ""
port: 0
network:
nodeBalancerConfigID: 12345
nodeBalancerID: 67890
region: us-ord 
```
This instead gets the NB and NB config ID if specified and uses those to fill out the controlPlaneEndpoint.
Fixes #
**TODOs**:
> [fix] add support for filling in controlPlaneEndpoint if only network info is specified

- Tiltfile
Deploying prometheus using Tilt sometimes take more than 60 seconds. In my case, it usually took 90 seconds.
```
prometheus │      NAME: prometheus
prometheus │      LAST DEPLOYED: Fri Jun 21 01:53:59 2024
prometheus │      NAMESPACE: monitoring
prometheus │      STATUS: deployed
prometheus │      REVISION: 1
prometheus │      NOTES:
prometheus │      kube-prometheus-stack has been installed. Check its status by running:
prometheus │        kubectl --namespace monitoring get pods -l "release=prometheus"
prometheus │
prometheus │      Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
prometheus │      Running cmd: ['helm', 'get', …
```
> fix: increase upsert timeout to 120 seconds

- cmd/main.go
- controller/linodecluster_controller.go
- controller/linodemachine_controller.go
- controller/linodeobjectstoragebucket_controller.go
- controller/linodevpc_controller.go
- observability/wrappers/interfaces.go
Adds options to configure controller concurrency and QPS/Burst values to the kube API server
Fixes #
**TODOs**:
> [feat] add controller concurrency options with elevated defaults

- controller/linodemachine_controller.go
- controller/linodemachine_controller_test.go
- util/reconciler/defaults.go
If too many requests are made to linodeAPI in a short span of time, it returns 429 error. This PR handles 429 errors and makes sure we retry creating machine after some time. Similarly, if there is client timeout or unexpected EOF errors, we get 002 as returncode. This PR handles those errors as well.
Fixes #
**TODOs**:
> fix: handle 429 and 002 errors during linodemachine creation

- cmd/main.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_test.go
**What this PR does / why we need it**: While @rahulait was performing scale testing, errors were seen on update and delete erroring out. e.g.:
```
2024-06-29T00:00:07Z	ERROR	LinodeMachineReconciler	Failed to get Linode machine instance	{"controller": "linodemachine", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "LinodeMachine", "LinodeMachine": {"name":"kubeadm4-md-0-65r6c-s8lqh","namespace":"default"}, "namespace": "default", "name": "kubeadm4-md-0-65r6c-s8lqh", "reconcileID": "b2070ab5-a216-4365-87f1-bfa2a2ee1076", "name": "default/kubeadm4-md-0-65r6c-s8lqh", "LinodeMachine": "kubeadm4-md-0-65r6c-s8lqh", "ID": 60786582, "error": "[502] Internal server error"}
2024-06-29T00:00:07Z	DEBUG	events	[502] Internal server error	{"type": "Warning", "object": …
```
> [fix] handle requeues for linode api errors on update and delete, set instance ID if linode already exists

- api/v1alpha1/linodemachinetemplate_types.go
- api/v1alpha2/linodemachinetemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
**What this PR does / why we need it**: This makes it so LinodeMachineTemplates aren't left behind after a `clusterctl move` operation.
Fixes #
**TODOs**:
> [fix] add move-heirarchy label to LMT

- cloud/scope/cluster.go
- cloud/scope/cluster_test.go
- cloud/scope/common.go
- cloud/scope/common_test.go
- cloud/scope/machine.go
- cloud/scope/machine_test.go
- cloud/scope/object_storage_bucket.go
- cloud/scope/object_storage_bucket_test.go
- cloud/scope/object_storage_key.go
- cloud/scope/object_storage_key_test.go
- cloud/scope/placement_group.go
- cloud/scope/placement_group_test.go
- cloud/scope/vpc.go
- cloud/scope/vpc_test.go
- cmd/main.go
- controller/linodecluster_controller.go
- controller/linodemachine_controller.go
- controller/linodeobjectstoragebucket_controller.go
- controller/linodeobjectstoragekey_controller.go
- controller/linodeplacementgroup_controller.go
- controller/linodevpc_controller.go
- docs/src/SUMMARY.md
- docs/src/topics/flavors/dns-loadbalancing.md
- docs/src/topics/getting-started.md
- go.mod
- mock/mocktest/suite_test.go
- Currently, CAPL does not allow targeting different Linode API instances for the domain client, and the client for the remaining resources. This use case is required by an internal project.
- Also, using custom CA certs is broken, due to the way CAPL initializes the linodego client (see below).
**Which issue(s) this PR fixes**: N/A
- Exposes new environment variables DNS Linode client configuration:
- `LINODE_DNS_URL` - equivalent of the `LINODE_URL`, but applies _only_ to the DNS client.
- `LINODE_DNS_CA` - equivalent of the `LINODE_CA`, but applies _only_ to the DNS client. If we target a different API instance than `LINODE_URL`, we might also need to provide different root CA certs.
- If the above are not …
> [feat] Support usage of separate Linode API for the domain client

- .github/workflows/e2e-test.yaml
- Makefile
This PR adds target in makefile to clean all child clusters. This will allow us to clean up resources when an e2e test run gets cancelled. We plan to always run the cleanup job to clean all child clusters when e2e test run finishes or gets cancelled.
Fixes #
**TODOs**:
> [fix] : always cleanup child clusters

- e2e/capl-cluster-flavors/kubeadm-flatcar-vpcless-capl-cluster/chainsaw-test.yaml
**What this PR does / why we need it**: Akamai / Linode support has been promoted to Flatcar Beta channel. Let's use this version in the test to get closer of what CAPL users would actually run. (https://github.com/flatcar/Flatcar/issues/1509) 
**Special notes for your reviewer**: Locally tested with `make e2etest E2E_SELECTOR='flatcar' E2E_FLAGS='--assert-timeout 10m0s'`
**TODOs**:
> [test]: bump Flatcar channel from Alpha to Beta

- hack/generate-flavors.sh
this PR adds some more conditionals in generate-flavors.sh to support the older bash versions shipped with MacOS.
Fixes #
**TODOs**:
> [CI] support older bash versions in generate-flavors.sh

- controller/suite_test.go
**What this PR does / why we need it**: We bumped envtest in https://github.com/linode/cluster-api-provider-linode/commit/83e70080e0ba92dd59b15dc0f9640f4f6e417efb but forgot to update the binary assets path accordingly. Not sure if we want to just do this or actually set this as an env var rather than just in the Makefile for downloading envtest if it doesn't exist.
Fixes #
**TODOs**:
> [fix] bump hardcoded envtest version

- .github/workflows/go-analyze.yml
**What this PR does / why we need it**: https://github.com/golangci/golangci-lint/releases/tag/v1.60.1 just came out and is causing go-analyze to fail on main. We should lock the version for now until we can address the necessary lint updates
Fixes #
**TODOs**:
> [ci] lock golangci-lint version for now

- cloud/scope/object_storage_key.go
- docs/src/topics/backups.md
- templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
CAPL clusterrs with etcd-backup-restore and related flavors fail to created. This is down to some recent OBJ changes for key names and namespaces within the secrets.
> [fix] fix etcd-backup-restore based flavors

- util/reconciler/defaults.go
It looks like we are too aggressive in checking whether the instance has moved from provisioning -> running state. When an instance is created, it comes up, gets its disks created and resized, boots up and finally becomes running. This operation itself takes 1 to 2 mins based on the size of instance and other factors. Currently during reconcile, we are checking if instance has moved from provisioning to running state every 5 secs. This means for each instance, we are making close to 12 to 20 GET calls. Here is a sample output for one instance:
```
// provisioning new instance
2024-08-20T13:24:08.426931642Z GET  /v4beta/linode/instances?page=1  HTTP/1.1
2024-08-20T13:24:08.516412267Z GET  /v4beta/regions/us-ord  HTTP/1.1 …
```
> check provisioning -> running every 15 secs instead of 5

- api/v1alpha2/linodemachine_types.go
this PR reverts the deprecation of firewallID to support the "bring your own" firewall use case outside of the new `LinodeFirewall` resource
Fixes #
**TODOs**:
> [fix] revert deprecation of firewall ID

- cloud/services/domains.go
- cloud/services/domains_test.go
- cloud/services/loadbalancers.go
- cloud/services/loadbalancers_test.go
- controller/linodecluster_controller_helpers.go
- controller/linodecluster_controller_test.go
Currently, if an individual node is deleted and a new one comes up, a DNS entry is appropriately created, but, the entry of the deleted node remains. This PR fixes the issue
> [fix] delete all stale entries for the domain

- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
- util/reconciler/defaults.go
**What this PR does / why we need it**: This changes the machine reconciler to check for the machine to be running less aggressively and changes the list instances to a get instance call based on the providerID if set. If there is no providerID, it is assumed an instance needs to be created. Additionally, we don't requeue if the bootstrap data isn't ready since a reconcile will be triggered automatically once it is ready.
Fixes #
**TODOs**:
> [cleanup][improvement] Machine controller cleanup, reduce API calls for Linode instances

- api/v1alpha2/linodefirewall_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
- controller/linodefirewall_controller_helpers.go
**What this PR does / why we need it**: The protocol was previously hard-coded to TCP. This change is necessary for other protocols to work like UDP.
Sample FW:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeFirewall
metadata:
name: sample-fw
spec:
enabled: true
inboundPolicy: DROP
inboundRules:
- action: ACCEPT
label: DHCP
ports: "68,546"
protocol: "UDP"
addresses:
ipv4:
- "0.0.0.0/0"
ipv6:
- "::/0"
label: node_traffic
ports: "1-65535"
protocol: "TCP"
addresses:
ipv4:
- 10.0.0.0/24
- action: ACCEPT
label: node_traffic
ports: "1-65535"
protocol: "UDP"
addresses:
ipv4:
- 10.0.0.0/24
```
Fixes #
**Special notes for …
> [fix] use protocol set by the firewall rule, add protocol validation

- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
**What this PR does / why we need it**: If a Firewall already exists with the same label, Firewall creation will fail and the resulting ID will be nil. This addresses that edge case.
Fixes #
**TODOs**:
> [fix] handle nil firewall ID if there is an error creating the Firewall referenced

- controller/linodecluster_controller.go
- controller/linodecluster_controller_test.go
- templates/infra/linodeMachineTemplate.yaml
We are currently relying on the credentials secret to fetch token for the linodeclient. The machine and cluster controllers rely on this to be present.
We need to block the deletion of said secret until all resources that rely on this secret are deleted.
Fixes #
**TODOs**:
> [fix] block credentials deletion until all dependent resources are cleaned up

- templates/addons/csi-driver-linode/linode-csi.yaml
> [improvement] add variable to set CSI chart version

- templates/infra/linodeFirewall.yaml
> allow all udp/icmp traffic along with tcp traffic within VPCs

- templates/flavors/k3s/dns-loadbalancing/kustomization.yaml
- templates/flavors/kubeadm/dns-loadbalancing/kustomization.yaml
- templates/flavors/kubeadm/konnectivity/kustomization.yaml
- templates/flavors/rke2/dns-loadbalancing/kustomization.yaml
- templates/infra/linodeFirewall.yaml
This PR tweaks firewall rules to be more accurate restrictive in the following ways:
Fixes #
**TODOs**:
> [improvement] update default firewall to restrict API server access and fix nodeport range

- util/helpers.go
- util/helpers_test.go
Changes the utility func which helps you ignore https status codes to accept multiple inputs of codes so you can ignore 2+ codes in the same check.
**Which issue(sa) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**TODOs**:
> Update IgnoreLinodeAPIError to accept multiple codes

- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- util/ratelimits.go
- util/ratelimits_test.go
First 5 POST requests take close to 5 secs or so. If we requeue subsequent requests with duration of 15 secs, then they will be next picked up at 20th second or so. This results in first 5 seconds of 15 sec window to not do anything. Since we are sleeping extra 5 or 6 secs in every 15 sec window, we end up taking additional 60+ seconds doing nothing when provisioning big clusters (say 100 node cluster). Ideally, we should sleep for 15 - 5 secs, i.e. 10 secs in this case. This PR takes account of ratelimit-reset value and uses that when requeueing.
Logs from cluster with new changes (bringing up 100 worker nodes)
```
k logs deploy/capl-controller-manager -n capl-system -f --timestamps > out.txt
cat out.txt  | grep "POST  /v4beta/linode/instances " | …
```
> [improvement] : retry on ratelimit-reset than always waiting for 15 secs

- controller/linodemachine_controller_helpers.go
- util/ratelimits.go
- util/ratelimits_test.go
- util/reconciler/defaults.go
Since the rate limits are now simplified to 5 req/15 secs, this PR updates CAPL to use that. Logs from a deployed cluster when worker nodes are scaled up from 0 to 100 nodes
```
cat logs/14oct/100nodes1.txt | grep "POST  /v4beta/linode/instances " | wc -l
100
cat logs/14oct/100nodes1.txt | grep "POST  /v4beta/linode/instances " | awk -F':' '{print $2}'  | sort -n | uniq -c | awk '{print $2 " - " $1}'
21 - 2
22 - 18
23 - 20
24 - 17
25 - 18
26 - 19
27 - 6
```
Time it took to bring up 100 nodes: 5 min 40 secs
Fixes #
**TODOs**:
> [improvement] : simplify rate limits as we now have only one limit for POST calls

- controller/linodemachine_controller_helpers.go
- util/vlanips.go
- util/vlanips_test.go
With the VLAN clusters, a in-memory map was maintained for each cluster's IPs. When the controller pod restarts, that IP map is lost, and any further cluster scaling activities cause the nodes to get overlapping IPs.
Fixes #
Testing steps
1. run `make local-deploy` off main
2. Create a cluster with the `rke2-vlan` flavor
3. Delete the capl-controller pod 
4. Increase the number of replicas in the `md`. describe the `linodemachines` and see that more than one linode has the same vlanIP
5. run `make local-deploy` off this branch
6. Delete one of the problem …
> [fix] make VLAN IPs unique across controller pod restarts

- controller/linodemachine_controller_helpers.go
> [fix] Use retryAfter() instead of static 10 sec delay for optimized POST call timing

- devbox.json
- devbox.lock
`make build` was failing on the main branch when code was checked out into a new directory and devbox shell was invoked.
```
abc@vm:~$ git clone git@github.com:linode/cluster-api-provider-linode.git test-code
Cloning into 'test-code'...
remote: Enumerating objects: 6821, done.
remote: Counting objects: 100% (1206/1206), done.
remote: Compressing objects: 100% (730/730), done.
remote: Total 6821 (delta 733), reused 750 (delta 431), pack-reused 5615 (from 1)
Receiving objects: 100% (6821/6821), 12.12 MiB | 23.03 MiB/s, done.
Resolving deltas: 100% (4456/4456), done.
abc@vm:~$ cd test-code/
abc@vm:~/test-code$ devbox install
Info: Ensuring packages are installed.
✓ Computed the Devbox environment.
Finished installing packages.
abc@vm:~/test-code$ …
```
> [fix] : pin kubebuilder to v4.2.0 and fix controller-gen

- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
This PR simplifies buildInstanceAddrs function and makes getInstanceConfigs call only when required(in case of vlan). Otherwise, it relies on the output of `/v4/linode/instances/<id>/ips` to get all ips associated with the instance.
**TODOs**:
> [improvement] : simplify addr calculation and fetch instance config only for vlans

- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
**What this PR does / why we need it**: Currently we can't define the VLAN interface to be on something other than eth0. This respects what VLAN interface is defined in the LinodeMachine if any.
Fixes #
**TODOs**:
> [fix] respect vlan interface if defined in linodemachine

- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_test.go
If create instance call fails due to context timeout error, instance gets provisioned on the linode side but CAPL thinks instance is still not created. It keeps on retrying and ends up hitting [400 label must be unique] error as it cannot provision another instance with same name. This results in CAPL continuously retrying to create the instance and ending up hitting rate-limits. This PR fixes the issue by doing a GET if instance already exists and using it during next reconciles.
Fixes #
**TODOs**:
> [fix] handle case where instance already exists

- cmd/main.go
- controller/linodemachine_controller.go
- controller/linodemachine_controller_helpers.go
- controller/linodemachine_controller_helpers_test.go
- controller/linodemachine_controller_test.go
**What this PR does / why we need it**: This adds support for gzipping the userData before base64 encoding it so we can fit more configuration into cloud-init.
Fixes #
**TODOs**:
> [improvement] Add env var toggle for gzip compression of cloud-init user data

- internal/controller/linodecluster_controller_test.go
- internal/controller/linodefirewall_controller_test.go
- internal/controller/linodemachine_controller_test.go
- internal/controller/linodevpc_controller_test.go
- util/reconciler/conditions.go
This PR makes sure we don't reset condition severity from error to warning during next reconciles. Last transition time for condition changes when its updated from warning to error. During next reconcile, if we look at the last reconcile time only, then it will be the updated time and current logic was assuming that time limit has not been reached and was flipping the condition back from error to warning.
Fixes #
**TODOs**:
> [fix] : avoid resetting condition with severity error to severity warning

- internal/controller/linodemachine_controller_helpers.go
- internal/controller/linodemachine_controller_test.go
We would like to use fixed backoff than exponential as exponential starts with microseconds and makes 10+ requests before it reaches 10 sec or higher backoff time. Since POST calls to /v4/linode/instances have low limits, we would like to make sure we don't make too many POST calls in case of an error due to exponential backoff. With this fix, we are now retrying at a fixed interval. This also affects other calls which use the same method to calculate how soon it should retry, but having a fixed interval for them is also fine.
Fixes #
**TODOs**:
> [improvement] : use fixed retryAfter instead of exponential backoff

- internal/controller/linodecluster_controller.go
- internal/controller/linodefirewall_controller.go
- internal/controller/linodemachine_controller.go
- internal/controller/linodemachine_controller_test.go
- internal/controller/linodeobjectstoragebucket_controller.go
- internal/controller/linodeplacementgroup_controller.go
- internal/controller/linodevpc_controller.go
- util/reconciler/conditions.go
> [improvement] Remove severity levels from controller logic

- .github/workflows/build_test_ci.yml
- .github/workflows/e2e-test.yaml
- Tiltfile
**What this PR does / why we need it**: 
Fixes #
**TODOs**:
> [ci][deps] pin capi operator version, skip e2e tests for markdown-only changes

- templates/flavors/rke2/etcd-disk/kustomization.yaml
- templates/flavors/rke2/full-vpcless/kustomization.yaml
- templates/flavors/rke2/full/kustomization.yaml
**What this PR does / why we need it**: The other flavors use diskSetup to convert it to disk_setup for cloud-init but for RKE2 it needs to be directly in cloud-init format to work.
Fixes #
**TODOs**:
> [fix] disk_setup for additional user data in RKE2

- .github/workflows/build_test_ci.yml
We use latest version of codecov cli when running codecov GHA. With release 0.9.0 and onwards, new endpoint is added and we need to allow it so that codecov cli and upload the results.
Fixes #
**TODOs**:
> [CI] : allow ingest.codecov.io so that codecov can work properly

- Makefile
- docs/.crd-ref-docs.yaml
- docs/src/SUMMARY.md
- docs/src/reference/out.md
- docs/src/reference/reference.md
This PR adds generation of handy API Docs for all resources, that the CAPL manages.
N/A
**TODOs**:
- I left the commits separate, to improve review process.
> [docs] generate API reference

- docs/src/SUMMARY.md
- docs/src/topics/cluster-object-store.md
Adds the Cluster Object Store documentation to the mdBook directory.
Fixes #
**TODOs**:
> [docs] add cloud-init boostrap via cluster object store to mdbook summary

- templates/addons/ccm-linode/ccm-linode.yaml
- templates/addons/cluster-resource-set/secret.yaml
- templates/flavors/k3s/default/kustomization.yaml
- templates/flavors/k3s/full-vpcless/kustomization.yaml
- templates/flavors/k3s/vpcless/kustomization.yaml
- templates/flavors/kubeadm/cilium-bgp-lb/kustomization.yaml
- templates/flavors/kubeadm/full-vpcless/kustomization.yaml
- templates/flavors/kubeadm/vpcless/kustomization.yaml
- templates/flavors/rke2/default/kustomization.yaml
- templates/flavors/rke2/vlan/kustomization.yaml
- templates/flavors/rke2/vpcless/kustomization.yaml
This PR allows CCM to work with different environments. Support to allow CAPL to work with different environments was added in https://github.com/linode/cluster-api-provider-linode/pull/546. This PR fixes CCM for child clusters. Along with other necessary vars required to provision a cluster, following vars also need to be set accordingly:
```
export LINODE_URL=<path of env's API>
export LINODE_CA=<env's CA file path on disk>
export LINODE_EXTERNAL_SUBNET=<network to be marked as public network>
export LINODE_CA_BASE64=<base64 encoded value of LINODE_CA>
```
Fixes #
**Special notes for your …
> [improvement] : allow CCM to work with different environments in CAPL

- templates/addons/csi-driver-linode/linode-csi.yaml
This PR allows us to run CSI driver in different environments.
NOTE: This PR is dependent on https://github.com/linode/linode-blockstorage-csi-driver/pull/348 to be merged and release v1.0.3 cut for csi driver.
Fixes #
**TODOs**:
> [improvement] : allow csi driver to run in different environments

- docs/src/SUMMARY.md
- docs/src/topics/linode-cloud-controller-manager.md
Adds documentation for CCM and relevant flags which needs to be set when running in custom environments
Fixes #
**TODOs**:
> [docs] : add doc for CCM

- Tiltfile
- docs/src/developers/development.md
- docs/src/topics/linode-cloud-controller-manager.md
We set both `LINODE_CA` and `LINODE_CA_BASE64` env vars. When `LINODE_CA` is set, we set `SSL_CERT_DIR` env var within the pod as we use [x509.SystemCertPool()](https://pkg.go.dev/crypto/x509#SystemCertPool) to set [root CAs](https://github.com/linode/cluster-api-provider-linode/blob/cb58ec3e8db7c2d9c0ee8e8003000169c7dcdb9a/cloud/scope/common.go#L81-L85).
`LINODE_CA_BASE64` is used to set CA content in secret used by child clusters as `clusterctl` doesn't allow us to read from file and set the content.
Instead of having two vars, we can remove one and just rely on `LINODE_CA_BASE64`.
Fixes # …
> [improvement] : remove LINODE_CA and use LINODE_CA_BASE64 only

- cloud/scope/common.go
Folks keep on using https://api.linode.com/v4 as LINODE_URL. This URL combines both url and api version. When set with SetBaseURL, it incorrectly adds additional /v4 to the URLs and those API calls will fail. Instead of using [SetBaseURL()](https://github.com/linode/linodego/blob/v1.46.0/client.go#L463), we should use [UseURL()](https://github.com/linode/linodego/blob/v1.46.0/client.go#L436) which correctly parses URLs and then itself calls SetBaseURL.
Fixes #
**TODOs**:
> [fix] : use UseURL to correctly parse URLs

- .chainsaw.yaml
Sometimes, e2e tests fail randomly because a deployment or resource is not ready in default 5min interval. Example failure:
```
l.go:52: | 16:26:13 | kubeadm-full-capl-cluster | @chainsaw                                       | CLEANUP   | END   |
=== NAME  chainsaw/rke2-capl-cluster
l.go:52: | 16:30:32 | rke2-capl-cluster | Check child cluster resources                | ASSERT    | ERROR | apps/v1/Deployment @ kube-system/rke2-coredns-rke2-coredns
=== ERROR
--------------------------------------------------------
apps/v1/Deployment/kube-system/rke2-coredns-rke2-coredns
--------------------------------------------------------
* status.availableReplicas: Invalid value: 1: Expected value: 2
* status.readyReplicas: Invalid value: 1: …
```
> [CI] : increase assert timeout from 5m to 10m

- config/manager/manager.yaml
- e2e/linodemachine-controller/metadata-gzip-compression/assert-capi-resources.yaml
- e2e/linodemachine-controller/metadata-gzip-compression/assert-linodemachine.yaml
- e2e/linodemachine-controller/metadata-gzip-compression/chainsaw-test.yaml
- e2e/linodemachine-controller/metadata-gzip-compression/check-linodemachine-deletion.yaml
- e2e/linodemachine-controller/metadata-gzip-compression/create-cluster.yaml
- e2e/linodemachine-controller/metadata-gzip-compression/create-linodemachine.yaml
Enables gzip compression by default for Linode's [Metadata service](https://techdocs.akamai.com/cloud-computing/docs/overview-of-the-metadata-service) when deploying Linode infrastructure instances.
Fixes #
The accompanying E2E test (`metadata-gzip-compression`) runs on the following suites/selectors: `linodemachine`, `all`
**TODOs**:
> chore: enable metadata gzip compression

- Makefile
- devbox.json
- devbox.lock
**Reason for change**:
The jq library is used by certain e2e tests, but it is not included in the devbox setup. If a user is running the tests without jq installed locally, some tests will fail because jq is not present.
When running `make e2etest` before the `/bin` directory has been created by `make tools` or `mkdir bin`, the command will fail because the `/bin` directory can't be found. One way to fix this would be adding `tools` to the dependencies for `e2etest`, but building the various tools individually (e.g. `make gowrap`) would still fail until the user makes the `/bin` directory. Instead, this change creates the directory any time any of the tools are built individually or with `make tools` (assuming it doesn't already exist). This also avoids needing to individually add the …
> [fix] Added jq devbox dependency and fixed missing /bin directory

- docs/src/topics/getting-started.md
**Reason for change**:
If the user doesn't set the `CONTROL_PLANE_MACHINE_COUNT` and `WORKER_MACHINE_COUNT` variables, the default cluster made by `clusterctl` has only one control plane node, which can cause issues when setting up deployments and services.
We can't change the `clusterctl` defaults, and modifying the template files doesn't resolve the issue: https://github.com/linode/cluster-api-provider-linode/pull/657.
**TODOs**:
> [docs] Add note about machine count variables

- cmd/main.go
- e2e/capl-cluster-flavors/kubeadm-flatcar-vpcless-capl-cluster/chainsaw-test.yaml
**What this PR does / why we need it**: In this PR, we bump Flatcar channel to Stable. Akamai support (with GZIP compression support for user-data) is now available on Stable since the latest release.
**Special notes for your reviewer**: This is not tested yet
**TODOs**:
> [test] bump Flatcar tested version to Stable

- .golangci.yml
- internal/controller/linodecluster_controller.go
- internal/controller/linodemachine_controller.go
Placement groups are not paused when a linode machine is paused, they must be paused as well.
Fixes #
**TODOs**:
> [fix] Pause placement group when pausing linode machine

- docs/src/topics/flavors/rke2.md
- templates/flavors/rke2/default/rke2ConfigTemplate.yaml
- templates/flavors/rke2/default/rke2ControlPlane.yaml
**What this PR does / why we need it**: RKE2 clusters have CIS hardening hard-coded to on. This makes that configurable and defaults it to off, mainly because templating the CIS_PROFILE is finicky. Trying to set the value to an empty string gets interpreted as unset which causes the empty value to be overwritten to enabled on the `clusterctl generate`.
Fixes #
**TODOs**:
> [improvement] toggle cis hardening for rke2 clusters

- internal/controller/linodefirewall_controller.go
- internal/controller/linodemachine_controller_helpers.go
- internal/controller/linodeplacementgroup_controller.go
- internal/controller/linodevpc_controller.go
Updated the Reconcile methods in LinodeFirewall, LinodePlacementGroup, and LinodeVPC controllers to allow for successful reconciliation when the associated cluster is not found during deletion. Added logging to indicate when a cluster is not found but the resource is being deleted, ensuring that the deletion process continues smoothly. Additionally, modified the pause logic to only check for paused conditions if the resource is not being deleted or if the cluster still exists.
Fixes #
**TODOs**:
> Refactor reconciliation logic in Linode controllers to handle deletion cases gracefully

- .github/workflows/build_test_ci.yml
- .github/workflows/e2e-upgrade-test.yaml
- Makefile
- e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
Some of our tests require a little bit more time to finish. We need to increase the assertion timeout time to 20m to account for those test. Also need to increase deletion timeout for kubectl commands in default-capl-cluster e2e test.
Fixes #
**TODOs**:
> Increase assert timeout for e2e test in GHA

- docs/src/SUMMARY.md
- docs/src/topics/flavors/nodeipam-ccm.md
- docs/src/topics/linode-cloud-controller-manager.md
- templates/addons/ccm-linode/ccm-linode.yaml
- templates/flavors/kubeadm/nodeipam-ccm/kustomization.yaml
This PR adds nodeipam-ccm flavor for kubeadm based clusters. It disables nodeipam controller within kube-controller-manager and enables it within CCM which does the ipv4 node ipam for the cluster.
Fixes #
**TODOs**:
> [feat] : add nodeipam-ccm flavor

- e2e/capl-cluster-flavors/k3s-capl-cluster/chainsaw-test.yaml
- e2e/capl-cluster-flavors/kubeadm-capl-cluster/chainsaw-test.yaml
- e2e/capl-cluster-flavors/rke2-capl-cluster/chainsaw-test.yaml
We not longer need to delete them explicitly since we have now implemented ownerRefs. Just deleting `Cluster` will cascade the deletion to all the other resources like `LinodeVPC`, `LinodeFirewall`, `LinodePlacementgroyp`, etc.
We are seeing the e2e tests fail because we are trying to delete resources that were already deleted when `Cluster` was deleted.
Fixes #
**TODOs**:
> [fix] Remove deletion of LinodeVPC and LinodeFirewall in e2etest

- cloud/scope/common.go
- cloud/scope/machine.go
- cloud/scope/machine_test.go
- cloud/scope/object_storage_key.go
- cloud/scope/object_storage_key_test.go
- cloud/services/object_storage_objects_test.go
- docs/src/topics/backups.md
- docs/src/topics/cluster-object-store.md
- docs/src/topics/flavors/flatcar.md
- e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
- e2e/linodemachine-controller/cluster-object-store/assert-key-and-secret.yaml
- e2e/linodemachine-controller/cluster-object-store/create-linodeobjectstoragekey.yaml
- e2e/linodeobjectstoragekey-controller/custom-secret/assert-key-and-secret.yaml
- e2e/linodeobjectstoragekey-controller/custom-secret/chainsaw-test.yaml
- e2e/linodeobjectstoragekey-controller/custom-secret/check-key-and-secret-deletion.yaml
- e2e/linodeobjectstoragekey-controller/custom-secret/create-linodeobjectstoragekey.yaml
- e2e/linodeobjectstoragekey-controller/deprecated-secret/assert-key-and-secret.yaml
- e2e/linodeobjectstoragekey-controller/deprecated-secret/chainsaw-test.yaml
- e2e/linodeobjectstoragekey-controller/deprecated-secret/check-key-and-secret-deletion.yaml
- e2e/linodeobjectstoragekey-controller/deprecated-secret/create-linodeobjectstoragekey.yaml
- e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/assert-key-and-secret.yaml
- e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/chainsaw-test.yaml
- e2e/linodeobjectstoragekey-controller/minimal-linodeobjectstoragekey/check-key-and-secret-deletion.yaml
- internal/controller/linodemachine_controller_helpers_test.go
- internal/controller/linodeobjectstoragekey_controller_test.go
- templates/addons/cluster-object-store/cluster-object-store.yaml
- templates/addons/etcd-backup-restore/etcd-backup-restore.yaml
- templates/addons/etcd-backup-restore/linode-obj.yaml
**What this PR does / why we need it**: This simplifies the field name for the OBJ Bucket Secret
Fixes #
**TODOs**:
> [breaking] Simplify field names for OBJ bucket, fix broken flatcar link in docs

- templates/addons/cilium/cilium.yaml
**What this PR does / why we need it**: In 1.17.4 we're seeing on new clusters:
```
2025-06-16T19:25:15.433227613Z stderr F time="2025-06-16T19:25:15.433184413Z" level=fatal msg="failed to start: daemon creation failed: unable to determine direct routing device. Use --direct-routing-device to specify it\nfailed to stop: unable to find controller ipcache-inject-labels" subsys=daemon
```
Setting `nodePort.directRoutingDevice` to eth0 in the cilium helm chart values does work but it takes a few minutes. In order to minimize cluster creation time, we'll just stick to 1.16.X.
Fixes #
**TODOs**:
> [fix,deps]: Downgrade cilium to 1.16.10

- .github/workflows/build_test_ci.yml
- .github/workflows/e2e-test.yaml
> [ci] pass environment setting for e2e workflow

- .github/workflows/build_test_ci.yml
- .github/workflows/go-analyze.yml
- .github/workflows/pull_request_ci.yaml
We are seeing `release-assets.githubusercontent.com` getting blocked in GHA runs. This PR allows all `*.githubusercontent.com`
Example: https://app.stepsecurity.io/github/linode/cluster-api-provider-linode/actions/runs/16310435533
Fixes #
**TODOs**:
> [CI] : allow all githubusercontent.com calls

- internal/controller/linodevpc_controller_helpers.go
- internal/controller/linodevpc_controller_test.go
**What this PR does / why we need it**: 
We currently filter the Linode API's ListVPCs response by both VPC ID and label when deciding whether to create a new VPC or update an existing one. This PR removes the latter filter and only checks for existing VPCs that match the ID found on the LinodeVPC resource. VPC ID is immutable and should be a sufficient filter for finding VPCs. Without this fix, any change to the VPC's label outside of CAPL will result in CAPL trying to create a new VPC when the underlying resource still exists.
Similarly, we currently build a map of subnets by label based on a list of VPC subnets we get from the Linode API. This method is vulnerable to the same issue in which any change to a subnet label after creation will prevent CAPL from reconciling the subnet …
> [fix] Make ID the source of truth for vpc and subnet names

- .github/copilot-instructions.md
> [chore] Add AI Agent (github copilot) instructions

- api/v1alpha2/linodecluster_types.go
- cloud/services/loadbalancers.go
- cloud/services/loadbalancers_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
- docs/src/reference/out.md
- hack/generate-flavors.sh
- internal/controller/linodecluster_controller_helpers.go
- internal/controller/linodecluster_controller_helpers_test.go
- internal/controller/linodecluster_controller_test.go
Feature-flagged support for VPC-scoped NodeBalancer backends. When enabled, control plane backends use VPC internal IPs and the NodeBalancer is created inside the target VPC. External traffic continues to egress via VPC NAT with a public IP.
- **API**: Add `spec.network.enableVPCBackends` (default `false`, immutable). When `true` and either `spec.VPCRef` or `spec.VPCID` is set, create the NodeBalancer in the VPC and prefer VPC backend IPs. Optional `spec.network.nodeBalancerBackendIPv4Range` is honored if provided.
- **Services**:
- New helpers: `ShouldUseVPC(scope)` and `DetermineAPIServerLBPort(scope)`.
- NodeBalancer creation uses VPC `SubnetID` and optional `IPv4Range`; backend registration prefers VPC internal IPs, falls back to Linode private IPs when the flag is disabled.
- …
> [feat] Add Support for VPC only backends

- internal/webhook/v1alpha2/linodecluster_webhook.go
- internal/webhook/v1alpha2/linodeclustertemplate_webhook.go
- internal/webhook/v1alpha2/linodemachine_webhook.go
- internal/webhook/v1alpha2/linodeobjectstoragebucket_webhook.go
- internal/webhook/v1alpha2/linodeobjectstoragebucket_webhook_test.go
- internal/webhook/v1alpha2/linodeplacementgroup_webhook.go
- internal/webhook/v1alpha2/linodevpc_webhook.go
- internal/webhook/v1alpha2/webhook_helpers.go
> [feat] remove defaultLinodeClient used by webhooks in favor of always using an authenticated client

- .golangci-kal.yml
- api/v1alpha2/addressset_types.go
- api/v1alpha2/firewallrule_types.go
- api/v1alpha2/linodecluster_types.go
- api/v1alpha2/linodeclustertemplate_types.go
- api/v1alpha2/linodefirewall_types.go
- api/v1alpha2/linodemachine_types.go
- api/v1alpha2/linodemachinetemplate_types.go
- api/v1alpha2/linodeobjectstoragebucket_types.go
- api/v1alpha2/linodeobjectstoragekey_types.go
- api/v1alpha2/linodeplacementgroup_types.go
- api/v1alpha2/linodevpc_types.go
> [improvement] enable the `optionalorrequired` linter for the various APIs

- api/v1alpha2/linodecluster_types.go
- api/v1alpha2/linodefirewall_types.go
- api/v1alpha2/linodemachine_types.go
- api/v1alpha2/linodemachinetemplate_types.go
- api/v1alpha2/linodeobjectstoragebucket_types.go
- api/v1alpha2/linodeobjectstoragekey_types.go
- api/v1alpha2/linodeplacementgroup_types.go
- api/v1alpha2/linodevpc_types.go
- internal/controller/linodecluster_controller.go
- internal/controller/linodecluster_controller_test.go
- internal/controller/linodefirewall_controller.go
- internal/controller/linodefirewall_controller_test.go
- internal/controller/linodemachine_controller.go
- internal/controller/linodemachine_controller_helpers.go
- internal/controller/linodemachine_controller_test.go
- internal/controller/linodemachinetemplate_controller.go
- internal/controller/linodeobjectstoragebucket_controller.go
- internal/controller/linodeobjectstoragebucket_controller_test.go
- internal/controller/linodeobjectstoragekey_controller.go
- internal/controller/linodeobjectstoragekey_controller_test.go
- internal/controller/linodeplacementgroup_controller.go
- internal/controller/linodevpc_controller.go
- internal/controller/linodevpc_controller_test.go
- internal/controller/suite_test.go
- util/reconciler/conditions.go
**What this PR does / why we need it**: Following up from https://github.com/linode/cluster-api-provider-linode/pull/590 and to prepare for updating the CAPI dependency (#858) we need to remove the v1beta2 conditions package
This is not breaking since we already changed the Conditions type in the Statuses to be `metav1.Conditions`, this just removes the package.
Fixes #
**TODOs**:
> [improvement] Remove v1beta2 conditions package

- .golangci-kal.yml
- api/v1alpha2/firewallrule_types.go
- api/v1alpha2/linodecluster_types.go
- api/v1alpha2/linodefirewall_types.go
- api/v1alpha2/linodemachine_types.go
- api/v1alpha2/linodemachinetemplate_types.go
- api/v1alpha2/linodeobjectstoragekey_types.go
- api/v1alpha2/linodevpc_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_firewallrules.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodefirewalls.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodemachinetemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodeobjectstoragekeys.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_linodevpcs.yaml
This PR enables the [SSATag](https://github.com/kubernetes-sigs/kube-api-linter/blob/main/docs/linters.md#ssatags) linter from KAL. as part of this all liststypes are now set to `atomic`, `set` or `map` with a `MapKey`, the way I selected which type to use is as follows:
* if a list is composed of go primitives(such as strings) then I use the `set` type, this does some deduplication but the places where we use this such as resource tags this would be unique values anyways
* if a list is composed of objects with a single key or single required key use a `map` type with the `mapKey` set to that value
* if the list is composed of objects with multiple required fields or all optional fields then set it to atomic
**Which issue(s) this PR fixes** …
> [improvement] enable SSA tag linter
